Jahia/content-editor

src/javascript/DesignSystem/Toggle/Toggle.jsx

The two colors are available now into the palette of js-components

BACKLOG-10525 remove override of palette colors

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/StaticFormDefinitionRegistry.java

Fix duplicate fieldset generated when a node type has a extends mixin declared in the CND

BACKLOG-10751 Fix duplicate fieldset

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/FieldsActions/unsetField.action.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/FieldsActions/unsetField.action.spec.js

https://jira.jahia.org/browse/BACKLOG-11447

BACKLOG-11447: set field touched when unset its value

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-11568

BACKLOG-11568 : use provided Jackson from core instead of embedding it.

---

src/javascript/Edit/engineTabs/engineTabs.utils.js

https://jira.jahia.org/browse/BACKLOG-11923

BACKLOG-11923 : use i18n labels for engine tabs

---

src/javascript/Edit/save/save.request.js

https://jira.jahia.org/browse/BACKLOG-12511

BACKLOG-12511 : call gwt refresh content function only if necessary

---

src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.scss
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
src/main/resources/jnt_globalSettings/js/globalSettings.contentEditor.jsp

In addition to this ticket I modified the name of the property containing
the link to academy from academyUrl to academyUrlWip to avoid this link
to be replaced by another one
https://jira.jahia.org/browse/BACKLOG-12981

BACKLOG-12981 : update wip modal labels, design and rename the wip link property

---

src/javascript/Api/ContentEditor.api.jsx

https://jira.jahia.org/browse/BACKLOG-12779 
fix Content Editor / GWT engines display issues
Covered by integration tests

BACKLOG-12779 : make content editor work properly with GWT modal windows

---

src/javascript/Edit/publish/publish.action.jsx
src/javascript/Edit/publish/publish.action.spec.js

https://jira.jahia.org/browse/BACKLOG-13053
disable publish button when content is in work in progress
covered by unit tests

BACKLOG-13053 : disable publish button for WIP contents

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/Validation/validation.utils.js
src/javascript/Validation/validation.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-13066
Use new action framework for save and edit action
Remove usage of `componentRendererAction` from `react-material`
Covered by unit tests

BACKLOG-13066 : use new action framework for create and save actions

---

src/javascript/Edit/startWorkflow/startWorkflow.action.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.spec.js

https://jira.jahia.org/browse/BACKLOG-13053
Make `Request publication` button disabled for `Work in progress` content.
Covered with Unit test

BACKLOG-13053 : fix request publication button display for WIP contents

---

src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/ContentPreviewMemoWrapper.jsx
src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/ContentPreviewMemoWrapper.spec.js

https://jira.jahia.org/browse/BACKLOG-13089
Page content have a preview but no id to "zoom" on it, so I not display the badge on page content

BACKLOG-13089: No display the "no preview badge" on page

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/ContentEditor.redux.jsx
src/javascript/ContentEditorHistory/ContentEditorHistory.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx

https://jira.jahia.org/browse/QA-12727
This sync GWT (old edit engines) language and content editor.
- Language use for GWT context is the one used to open Content Editor.
- We restore the GWT language to the one that was used to open content editor when editor is closed. 
Covered by integration test.

QA-12727 : sync language between GWT and Content Editor

---

src/javascript/DesignSystem/ContentTable/ContentTable.jsx
src/javascript/DesignSystem/ContentTable/ContentTable.spec.js
src/javascript/DesignSystem/ContentTable/ContentTableHeader/ContentTableHeader.jsx
src/javascript/DesignSystem/ContentTable/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/List/List.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12893:
Sort content editor pickers

BACKLOG-12893: sort all column of the picker when in list view

---

src/javascript/Edit/Edit.jsx
src/javascript/FormDefinitions/FormDefinitions.js

https://jira.jahia.org/browse/BACKLOG-13364
This to avoid Content Editor to be re rendered multiple times.

BACKLOG-13364 : avoid to reload Content Editor many times

---

src/javascript/AddMixin.register.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/MultipleField.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Checkbox/Checkbox.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/MultipleSelect/MultipleSelect.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/MultipleSelect/MultipleSelect.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/DateTimePicker/DateTimePicker.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerContainer.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerContainer.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.test.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Text/Text.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Text/Text.test.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/TextArea/TextArea.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/TextArea/TextArea.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SingleField.jsx

https://jira.jahia.org/browse/BACKLOG-13915
This PR adds a onDestroy props on Selector components that allow to trigger onChange when the Selector is unmounted onChange(previousValue, undefined)
Covered with unit tests

BACKLOG-13915 : trigger onChange when a selector is removed from the DOM

---

src/javascript/FormDefinitions/FormData.adapter.js
src/javascript/FormDefinitions/FormData.adapter.spec.js

https://jira.jahia.org/browse/BACKLOG-13946

BACKLOG-13946 set system name to readonly when node is locked

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx

https://jira.jahia.org/browse/BACKLOG-14312
* Changed Required badge colour to "info" and Shared by all languages badge colour to "primary"
* Affects Field and ChildrenSection components

BACKLOG-14312: Reversed Colours for "Required" and "Shared by all languages" Badges

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-14546

BACKLOG-14546 : bump app shell to 2.1.0

---

src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.jsx
src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.md
src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.scss
src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.spec.js
src/javascript/SelectorTypes/Picker/PickerDialog/LeftPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/LeftPanel.scss
src/javascript/SelectorTypes/Picker/PickerDialog/LeftPanel.spec.jsx

https://jira.jahia.org/browse/BACKLOG-15112
Replaces the SiteSwitcher component in LeftPanel with the Moonstone Dropdown component and wires it up accordingly.

BACKLOG-15112: Change site switcher in picker modal to moonstone dropdown

---

src/javascript/SelectorTypes/ChoiceList/ChoiceList.actions.js
src/javascript/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/QA-13585
Updated the way the `isShowIcons` prop is passed into the `menuAction` so that the icons appear properly.

QA-13585: Missing icons in 3 dots menu in Content Editor

---

src/javascript/SelectorTypes/Picker/Picker.configs.js
src/javascript/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/BACKLOG-15623
Fixes the issue where the 3 dots more actions menu was not appearing for the FilePicker.

BACKLOG-15623: Add more actions menu for FilePicker

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ManualOrdering/ManualOrdering.jsx

https://jira.jahia.org/browse/QA-13338
There is an existing logic flaw not considering the existing drop item in the array
We need to take that into consideration for 'childrenWithoutDropped'

QA-13338 Fixing a logic bug here where not considering the index of drop item

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ManualOrdering/ManualOrdering.jsx

https://jira.jahia.org/browse/QA-13338
Simplified the index portion (remove duplicated +1)
Change back to use slice as splice returns the removed element instead of the modified array
Thought of this is more readable as passing childrenWithoutDropped would not make sense

QA-13338 fixing minor re-factor bug on the display as splice returns the removed element

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx

https://jira.jahia.org/browse/BACKLOG-15846
Fixed a bug where mixin helper text is still indented even without a toggle. Removed hardcoded indent and added a wrapper div around labels so that it flows automatically if toggle is present:

BACKLOG-15846: Add wrapper div around fieldset label

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx

https://jira.jahia.org/browse/BACKLOG-15732
Fixed layout wrapping issue for helper mixin.
From this: 
to this:

BACKLOG-15732: Fix wrap on long mixin helper texts

---

src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx

https://jira.jahia.org/browse/QA-13833
See ticket for scenario.
Modify logic to show unmark WIP option by checking for both single language and multilanguage WIP nodes, as long as it's single language.

QA-13833: Add unmark WIP option for previous multi-language WIP

---

src/javascript/SelectorTypes/SystemName/SystemName.utils.jsx

https://jira.jahia.org/browse/QA-14023
When you add a page, if you set the title "C'est chouette", the generated system name is "c'est-chouette". 
We should avoid quotes in system name; it's a source of troubles.
On Jahia 7, the quote was removed.

QA-14023 Remove quote char

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-14015
use explicit long in choicelist values of long

QA-14015 : use explicit long in choicelist values of long

---

src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/EditPanelContent/Preview/Preview.fetcher.js
src/javascript/FormDefinitions/FormDefinitions.js
src/javascript/PublicationInfo/PublicationInfo.jsx
src/javascript/SelectorTypes/Category/Category.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/Thumbnail/Thumbnail.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/QA-14183
Display error message instead of throwing error. 
Fix label for errors about querying content

QA-14183: Do not throw error if RichText can not read CKeditor config

---

src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.spec.jsx
src/javascript/FormDefinitions/FormDefinitions.js
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java

…n redux mode  (#1040)
* QA-14183: Handle errors differently in ContentPath, avoid doing refetchObservables in Edit.jsx, handle PathNotFpundException exceptions on GraphQL side. Return default configuration if needed for CKeditor
* QA-14183: Avoid calling dispatch to pcNavigateTo if not calling from PageComposer
https://jira.jahia.org/browse/QA-14183

QA-14183: port from 3.3.2 to 3.4.0

---

src/javascript/DesignSystem/ContentTable/ContentRow.jsx

https://jira.jahia.org/browse/BACKLOG-16953
Avoid endless render loop in SubContentCountLazyLoader because of redefined "updateRow" callback

BACKLOG-16953: Use stable callback

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/Create/Create.jsx
src/javascript/Edit/Edit.jsx
src/javascript/Lock/LockManager.js

https://jira.jahia.org/browse/QA-13660
Adds a onClosedCallback that is called when the engine is completely closed (and locks released, if any)
In edit mode, refresh only when the lock has been released. If no lock is set, it means the content was in readonly and therefore no need to reload.
In create mode, refresh when the Create is closed. If Create is closed to open an Edit (when clicking on save), refresh is not called - it's done only when the Edit dialog is closed.

QA-13660: refresh only when closing edit/create

---

src/javascript/Edit/engineTabs/engineTabs.utils.js

https://jira.jahia.org/browse/BACKLOG-16486
Prevent locking twice the node, as we are already in content-editor with a global lock on the current node. Since locks are not reentrant, opening an advanced tab tries to add another lock without success, but closing it remove the content-editor lock.

BACKLOG-16486: Skip locking

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Validation/validation.utils.js
src/javascript/Validation/validation.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-17108
Return errors from validation, this allows us to use them without waiting for the next render cycle when they become available via context

BACKLOG-17108 Return errors from validation

---

src/main/java/org/jahia/modules/contenteditor/api/lock/StaticEditorLockService.java

https://jira.jahia.org/browse/BACKLOG-16486
Use ConcurrentMap locking instead of synchronization. Ensure we don't have multiple unlocks happening at the same time by wrapping operations in map.compute .

BACKLOG-16486: Refactor lock handling

---

src/javascript/ContentEditor.register.jsx
src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/EditPanel/header/HeaderBadges/HeaderBadges.jsx
src/javascript/EditPanel/header/HeaderBadges/HeaderBadges.spec.jsx
src/javascript/EditPanel/header/HeaderBadges/index.js
src/javascript/EditPanel/header/UpperSection.jsx
src/javascript/EditPanel/header/UpperSection.spec.js

* https://jira.jahia.org/browse/BACKLOG-16835
* https://jira.jahia.org/browse/BACKLOG-17125
* Enable CE modal when in edit mode
* Refactor header badges into a component
* Add badges in Edit panel modal
* BACKLOG-17125: Remove badges in CE fullscreen create mode

BACKLOG-16835: Enable CE modal in edit mode

---

src/javascript/SelectorTypes/RichText/RichText.jsx
src/javascript/Validation/validation.utils.js
src/javascript/Validation/validation.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-17169
Issue is due to ckeditor blur event revalidating the form after the server error has been received and parsed. By default ckeditor send blur event 200ms after effective blur, causing it to happen some times after server return .. removing the delay make it behave like other fields, sending the blur and triggering validation even before the save onclick event is received.
Also removed duplicate validation in setErrorFieldTouched.

BACKLOG-17169: Removed ckeditor blur delay

---

src/javascript/SelectorTypes/Category/category.adapter.js

There is a client ticket recently opened which lead me to this issue (MP for more details), there is a workaround but not really easy nor compatible with production so it's quite critical on our side.
Jahia 8.1.0.1
Content-Editor 3.4.0
Create a website with a language country like `en_US` and another of your choice (it can simply be `en`)
Add the news module to the website.
Create a category in simple english `en` with 2 sub categories:
```
- Cat1
- SubCat1
- SubCat2
```
Go to page-composer to edit the website
Make sure you are editing in `en_US`
Add the component `Last news retrieving` => Error with localeCompare
This is because in JS localeCompare expect a locale to be dash separated not underscore. so it will work fine if you replace underscore by dash.
As commented in the file this PR …

QA-14323: JS localCompare issue

---

webpack.config.js

Use rules provided by moonstone package to correctly compile moonstone , including the styleloader attribute required by jcontent.
Replace file-loader with asset/resource.

Fixed moonstone compilation, use integrated rules

---

src/javascript/SelectorTypes/Picker/registerPicker.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx

https://jira.jahia.org/browse/BACKLOG-17311
Ensure we have a key for 'Picker in 'data-sel-content-editor-field-type' and also add the picker configuration key (image,file,etc..) in data-sel-content-editor-field-picker-type

BACKLOG-17311: Ensure we have a key for 'Picker'

---

src/javascript/ContentEditor/EditPanel/I18nContextHandler.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx
src/javascript/contexts/ContentEditor/ContentEditor.context.js
src/javascript/utils/useSwitchLanguage.js

https://jira.jahia.org/browse/BACKLOG-17314
https://jira.jahia.org/browse/BACKLOG-17322
Revert #1167 as onChange/useEffect cannot work in sync.
Add a "count" update on every language change, after i18n values have been set.
Use new CKEditor when language and values have changed.
Also fix the useSwitchLanguage where unchanged i18n values were lost (BACKLOG-17230)

Revert previous changes for BACKLOG-17314, use a switch language count instead

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
tests/cypress/e2e/createContent.cy.ts
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/fixtures/pickers/contentTypes.ts
tests/cypress/fixtures/pickers/createContent.graphql
tests/cypress/fixtures/pickers/createFolder.graphql
tests/cypress/fixtures/pickers/deleteContent.graphql
tests/cypress/fixtures/pickers/deleteFolder.graphql
tests/cypress/fixtures/pickers/install-qa-module.yaml
tests/cypress/page-object/accordionItem.ts
tests/cypress/page-object/pageComposer.ts
tests/cypress/page-object/picker.ts
tests/cypress/page-object/tableHeaderRow.ts
tests/cypress/utils/assertUtils.ts
tests/cypress/utils/index.js
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-17237
Few cypress base test cases to cover the picker epic story and to expand on for more detailed scenarios (see covered scenarios in ticket).
Also added a `data-sel-role` for the picker dialog to target in tests.
Currently failing a test until https://jira.jahia.org/browse/BACKLOG-17572 (check for type column in table) and https://jira.jahia.org/browse/BACKLOG-17503 (table missing on content folders) is resolved.

BACKLOG-17237 - Add picker dialog cypress tests

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-17577
Remove duplicate selection state, do not use inputContext in dialog (unusable from a richtext). Use initialSelectedItem for initial state, as a path or path array.
Fixed onClose in RichText

BACKLOG-17577: Fixed picker selection

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/SelectionCaption/SelectionCaption.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/SelectionCaption/SelectionCaption.scss
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/actions/openInTabAction.js
src/javascript/SelectorTypes/Picker/actions/openInTabAction.spec.js
src/javascript/SelectorTypes/Picker/configs/ContentPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/MediaPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.js
src/javascript/SelectorTypes/Picker/reactTable/plugins/useRowSelection.jsx

https://jira.jahia.org/browse/BACKLOG-19887
Changed the "usePickerInputData" so that it always takes an array of uuid and return an array of fieldData. 
Directly put nodes in redux selection instead of transformed data.
Fixed caption layout, use nodeIcon to display icon based on the node

BACKLOG-19887: improve caption

---

src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/registerPicker.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.container.spec.jsx

https://jira.jahia.org/browse/BACKLOG-19874

BACKLOG-19874: Use default picker if no type is specified (3 accordions)

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19909
Add picker config to avoid using jcontent's path

BACKLOG-19909 Add picker config to avoid using jcontent's path

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/accordionItems/queryHandlers.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/reactTable/plugins/useExpanded.jsx

https://jira.jahia.org/browse/BACKLOG-17381
Adapted useLayoutQuery usage.
Add picker-pages-tree , picker-conten-folder-tree and picker-folder-tree accordions . Also adapt picker-category and reformatted accordionItems code.
Adapted picker configs
Fixed the "useExpanded" so that we can select without expanding and expand without selecting.

BACKLOG-17381: Adapt queryHandlers, add page/folder/contentfolder modes

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerSiteSwitcher.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/index.js
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/accordionItems/queryHandlers.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19924
- Add site switcher
- Add openable types in table ( navMenuItem for page picker, folder and content folder )
- Automatically expand first node only
- Set columns

BACKLOG-19924: Add site switcher and openable types in tree

---

tests/env.run.sh

https://jira.jahia.org/browse/BACKLOG-19953
Current directory was changed when we added groovy script execution [here](https://github.com/Jahia/content-editor/pull/1265/files?w=1) which was causing the `jahia-reporter` execution to fail.
Fixed to go back to home directory, and also for `jahia-reporter` to use home directory in path instead of current dir.

BACKLOG-19953: Fix cypress container script

---

src/javascript/SelectorTypes/Picker/registerPicker.js

https://jira.jahia.org/browse/BACKLOG-19937
while testing custom pickers with selenium I noticed we were using editorial picker which causing even more issues than if it was default

BACKLOG-19937: Fallback to default configuration if it does not exist or if it is a legacy configuration

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/EditorialLinkContentTypeSelector.jsx
src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/EditorialContentTypeSelector.js
src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js
src/javascript/SelectorTypes/Picker/configs/editorialPicker/index.js
src/javascript/SelectorTypes/Picker/configs/queryHandlers.jsx

https://jira.jahia.org/browse/BACKLOG-17575
Every ContentTypeSelector can define its own rules to be displayed or not, ContentLayout.container cannot hide generic header based on custom rule. Ensure the query does not use viewType if selector is not defined ( for editorial and editorialLink )

BACKLOG-17575: check page type in ContentTypeSelector

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx

https://jira.jahia.org/browse/BACKLOG-19992
Mount a folder with lots folders/files (I have my modules folder mounted under /var/jahia/sources) the editorialpicker will recurse in the files folder and try to find pages and mainResource in there but as jnt:folder is not excluded it keeps going down the rabbit hole

BACKLOG-19992: Do not recurse into files folder of sites

---

src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
tests/cypress/e2e/pickers/displayActions.cy.ts
tests/cypress/page-object/picker.ts

https://jira.jahia.org/browse/BACKLOG-17389
* Reuse refresh action from jcontent and add to picker targets
* Add cypress test for refresh

BACKLOG-17389: Add refresh to pickers

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-17389
Embed refresh button for all pickers instead of dynamically targeting `DisplayActions`

BACKLOG-17389: Refactor picker refresh button

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.scss

https://jira.jahia.org/browse/BACKLOG-19873

BACKLOG-19873: Add disabled styling for non-selectable items in structured view

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/actions/registerPickerActions.js
src/javascript/init.js

…
https://jira.jahia.org/browse/BACKLOG-19987
Allow to customize accordions used by a picker directly from the picker. Allow to pass accordionItemsProps directly from the picker config
https://docs.google.com/document/d/1WyI_EMJA9K6r6NYJzC7ZJiE-yCJBuMcITGrBW-vf5IE/edit#

BACKLOG-19987: Allow to customize accordions used by a picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/registerPicker.js
src/javascript/SelectorTypes/resolveSelectorType.js
tests/cypress/e2e/pickers/pickerDefaults.cy.ts
tests/cypress/fixtures/pickers/contentTypes.ts

https://jira.jahia.org/browse/BACKLOG-19961
* Add default pickers based from CND type constraints by matching `selectableTypesTable` attribute in the picker config
* Add cypress test

BACKLOG-19961: Add default pickers by type constraint

---

src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx
tests/cypress/e2e/pickers/site.cy.ts

https://jira.jahia.org/browse/BACKLOG-20101
It looks like including `jmix:navMenuItem` to typeFilter also returns `jnt:page` in the results.
Filter out page-like node types when view type is not pages

BACKLOG-20101: Add page-type filter for content view

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.spec.jsx

https://jira.jahia.org/browse/BACKLOG-17144

BACKLOG-17144: avoid calling onChange if previousValue and currentValue are the same

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx

https://jira.jahia.org/browse/BACKLOG-20150
Remove wip selector on shared lang badge

BACKLOG-20150 Remove wip selector on shared lang badge

---

.github/maven.settings.xml
pom.xml
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/nt_base.hidden-layout.json
tests/cypress/e2e/pickers/site.cy.ts
tests/cypress/page-object/pickerTable.ts

https://jira.jahia.org/browse/BACKLOG-20201
* Revert the 4.1.0 release and update the module dependencies to make it clear we need:
*  jahia-parent 8.1.1.0
* app-shell=2.7+
* graphql-dxm-provider=2.13+
* jcontent=2.8+
* Update module dependencies
* Fix failing tests due to a change in definitions loaded https://github.com/Jahia/content-editor/blob/master/src/main/resources/META-INF/jahia-content-editor-forms/forms/nt_base.json#L2
* This form definition was loaded during test init before ([here](https://github.com/Jahia/content-editor/blob/master/src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java#L103)) but is ignored due to missing nodeType attribute
* Now that `nodeType` attribute has been added, it is now loaded during tests and affected …

BACKLOG-20201: Update module dependencies; Fix CE tests

---

src/javascript/actions/registerEditActions.js

https://jira.jahia.org/browse/BACKLOG-20114
Allow to get edit Actions in headerPrimary and in selectedContentActions

BACKLOG-20114: register edit actions in extra targets

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx

https://jira.jahia.org/browse/QA-14194
Add a condition to make sure node belongs to folder before doing any state updates

QA-14194 Add a condition to make sure node belongs to folder

---

src/javascript/SelectorTypes/Boolean/Boolean.jsx
src/javascript/SelectorTypes/Boolean/Boolean.scss

https://jira.jahia.org/browse/BACKLOG-20212
BACKLOG-20212: Ensure that checkbox is disabled so that clicking/hovering the label do not trigger changes, update style to avoid effect if disabled

BACKLOG-20212: Ensure that checkbox is disabled so that click/hover label does nothing

---

src/javascript/ContentEditor/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/ContentEditor/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.spec.jsx

https://jira.jahia.org/browse/BACKLOG-16839

BACKLOG-16839: Display language switcher only for multi-language sites

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.scss

https://jira.jahia.org/browse/SELENIUM-1560
Fix issue with selenium scrolling the fields but end up behind the sticky section title. 
Add scroll margin for fields to account for the sticky section title height.

SELENIUM-1560: Add scroll margin for fields

---

src/javascript/ContentEditor/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/ContentEditor/edit.gql-queries.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/languageSwitcher.cy.ts
tests/cypress/page-object/contentEditor.ts

https://jira.jahia.org/browse/BACKLOG-16838
Depends on this PR: https://github.com/Jahia/graphql-core/pull/277
Refactor language dropdown to split into option groups depending on whether language already has been translated or currently filled in edit mode.
Added cypress tests for language switcher as well.

BACKLOG-16838: Separate non-filled languages in language switcher

---

src/javascript/ContentEditor/ContentEditor.jsx
src/javascript/ContentEditor/EditPanel/EditPanelCompact.jsx
src/javascript/ContentEditor/EditPanel/EditPanelHeader/EditPanelHeader.jsx
src/javascript/ContentEditor/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/ContentEditor/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.spec.jsx
src/javascript/actions/jcontent/editContent/editContentAction.jsx
src/javascript/shared/index.js
yarn.lock

Expose various component to be able build a custom layout for Content Editor
Allow to provide a configuration to content editor action
Remove unused property from the site switcher

BACKLOG-20431 : expose content editor components

---

src/javascript/SelectorTypes/Text/Text.jsx
src/javascript/shared/index.js
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

Expose adapters and corresponding graphql queries
Fix 2 NPE:
- one in Text when the component is loaded 
- one in FieldSet when an override has no need to be moved to a different section

BACKLOG-20514 : expose edit / create adapters + few NPE fixes

---

src/javascript/ContentEditorApi/ContentPickerApi.jsx
src/javascript/ContentEditorApi/index.js
src/javascript/SelectorTypes/Picker/Picker.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/Row.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/SelectionCaption.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx
src/javascript/SelectorTypes/RichText/RichText.utils.js
src/javascript/SelectorTypes/RichText/RichText.utils.spec.js
src/javascript/register.jsx
src/javascript/shared/index.js

https://jira.jahia.org/browse/BACKLOG-20448
Adds a new entry point in the CE api to call the picker (openPicker) so that it can be used in any other 3rd party integration, including richtext editors. Moved the code from RichText to this ContentPickerApi to open a picker based on the state.
The main issue was that a few parameters were taken from CE context (lang, uilang, multiple, editorContext.site), which cannot be used if we want to be able to use the picker outside of CE. Instead pass these paramters to the openPicker api and propagate props until where they are used.
Also cleaned RichText.utils to use proper parameters.

BACKLOG-20448: Uncontextualize content picker and allow usage in API

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx

https://jira.jahia.org/browse/QA-14687
4.2.2 backport of https://github.com/Jahia/content-editor/pull/1525

QA-14687: Exclude users and groups folder when recursing editorial link picker

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/editorialLinkPicker.js

https://jira.jahia.org/browse/QA-14639

QA-14639: Enforce natural/JCR sorting when opening editorial link picker

---

src/javascript/utils/fields.utils.js
src/javascript/utils/systemName.utils.js
src/javascript/utils/useSwitchLanguage.js
tests/cypress/e2e/systemNameTest.cy.ts

https://jira.jahia.org/browse/BACKLOG-20464
When an i18n property is set use the current system name across all languages

BACKLOG-20464: Store current system name, if an i18n property has been updated before switching language

---

src/javascript/actions/contenteditor/create/createAction.js
src/javascript/contexts/ContentEditor/ContentEditor.context.js

https://jira.jahia.org/browse/BACKLOG-20659
Reverted PR change from BACKLOG-17202 as it's causing regression.
As alternative solution, trying to fully reset i18n context. I'm not sure if there's some reasoning behind keeping previous values on i18n reset (I'm hoping cypress test results will tell me...)

BACKLOG-20659: Fully reset i18n context

---

src/javascript/ContentEditor/Create.jsx
src/javascript/contexts/ContentEditor/ContentEditor.context.js
tests/cypress/e2e/createContent.cy.ts
tests/cypress/e2e/createContentI18N.cy.ts
tests/cypress/e2e/pickers/pdf.cy.ts
tests/cypress/e2e/pickers/pickerMultiple.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/languageSwitcher.ts

https://jira.jahia.org/browse/BACKLOG-17201
Move `createAnother` state to content-editor context to persist when switching languages during create.

BACKLOG-17201: Persist 'create another' checkbox state

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx
src/javascript/ContentEditorApi/OnCloseConfirmationDialog.jsx

https://jira.jahia.org/browse/BACKLOG-20731
Push contentEditor location state if CE not opened yet otherwise replace. 
Add location.hash useEffect onConfirmationDialog

BACKLOG-20731: Push contentEditor location state if CE not opened yet

---

src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_category.json
tests/cypress/e2e/categories.cy.ts

https://jira.jahia.org/browse/BACKLOG-20548
- Use overrides to only display Content section (hide seo);
- Add cypress test:
- Content section only visible for categories
- Only display certain items in advanced options (see https://github.com/Jahia/jahia-private/pull/1608 )

BACKLOG-20548: Only display Content section in CE for categories

---

src/javascript/actions/registerCreateActions.js
src/javascript/actions/registerEditActions.js
src/main/resources/configs/contentEditor.jsp

https://jira.jahia.org/browse/BACKLOG-20547
Modify actions to work with new Category Manager

BACKLOG-20547: Register actions for jnt:category on use showCatMan flag to register Edit in headerPrimary

---

src/javascript/ContentEditor.constants.js
src/javascript/validation/validate.js
src/javascript/validation/validate.spec.js

https://jira.jahia.org/browse/QA-14633
- Do equals comparison instead of regex comparison for choicelist values
- Added test cases in validation.spec.js

QA-14633: Use equals comparison for validating choicelist values

---

tests/cypress/e2e/contentEditorForm.cy.ts
tests/cypress/fixtures/createSite.groovy
tests/jahia-module/pom.xml
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/META-INF/jahia-content-editor-forms/fieldsets/cent_testDefaultTemplate.json

https://jira.jahia.org/browse/QA-14376
Add priority value in json override to move `j:templateName` field from `jmix:hasTemplateNode` fieldSet to `cent:testDefaultTemplate` to be able to set readOnly

QA-14376: Add cypress test for default template value, readonly

---

src/main/java/org/jahia/modules/contenteditor/graphql/api/forms/GqlEditorForms.java
src/test/java/org/jahia/modules/contenteditor/utils/ContentEditorUtilsTest.java

https://jira.jahia.org/browse/QA-14593

QA-14593: use jmix:droppableContent instead of jmix:editorialContent

---

src/javascript/SelectorTypes/RichText/RichText.utils.js

…
https://jira.jahia.org/browse/QA-15049
Backport changes done in JContent

QA-15049: Backport fix to 4_5_x. Dialog may not have field for alternate title (html5video plugin for example)

---

.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
pom.xml
tests/jahia-module/pom.xml

Due to the state of master, we were previously stuck into the 45x branch, now that this is cleaned, the next release of content-editor can be 4.6.0

TECH-1573: Updated version and signature

---

tests/cypress/e2e/contentMultiLanguage.cy.ts
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/e2e/pickers/search.cy.ts
tests/cypress/e2e/textFieldInitializerTest.cy.ts
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-22196

BACKLOG-22196: Fix tests

---

src/javascript/editorTabs/AdvancedOptions/VanityUrls/VanityUrls.jsx

https://jira.jahia.org/browse/BACKLOG-22904
Follow-up to https://github.com/Jahia/content-editor/pull/1730 as backport to [QA-14983](https://jira.jahia.org/browse/QA-14983) from https://github.com/Jahia/jcontent/pull/1044.
Fix translation namespace from `jcontent` to `content-editor`

BACKLOG-22904: Fix translation namespace for vanity url label

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-15247
Fixing regression where the latest backport (https://github.com/Jahia/content-editor/pull/1745) override the check for empty selectorOptions (which was added here https://github.com/Jahia/content-editor/pull/1737/files?w=1#diff-00e38d6027e73906ae3862e36de5a9ad3f3f0d78bea54efbfc80c471b9e145d7R891) 
Re-add check for `!selectorOptions.isEmpty()`

QA-15247: Re-add missing check for empty selectorOptions

---

src/javascript/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/SelectorTypes/DateTimePicker/DateTimePicker.spec.js
src/main/resources/META-INF/configurations/org.jahia.modules.contentEditor.cfg

Provide a way to override date format in date time selector type using a configuration name forceDateFormat (DD/MM/YYYY, MM/DD/YYYY are only valid format)
https://jira.jahia.org/browse/BACKLOG-23452

BACKLOG-23452: Provide a way to override date format in date time selector type

---

src/javascript/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/SelectorTypes/DateTimePicker/DateTimePicker.spec.js

https://jira.jahia.org/browse/BACKLOG-23452
When a date format is configured in _Content Editor_ (`contentEditor.forceDateFormat` property), trim its value to loose restrictions on this property (as the value **must** be `'MM/DD/YYYY'` or  `'DD/MM/YYYY'`).
Similar to https://github.com/Jahia/jcontent/pull/1389 done for _Jcontent_.

BACKLOG-23452: Trim the date format when configured

---

pom.xml
src/javascript/ContentEditor/updateNode/updateNode.gql-mutation.js
src/javascript/utils/fields.utils.js
src/javascript/utils/fields.utils.spec.js
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/QA-15315

QA-15315 Backport from jcontent, clearing multiple localized props
