Jahia/content-editor

src/javascript/EditPanelContainer/EditPanel/EditPanel.utils.js
src/javascript/EditPanelContainer/EditPanel/EditPanel.utils.spec.js
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/SelectorTypes/MediaPicker/MediaPickerDialog/MediaPickerDialog.gql-queries.js
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/SelectorTypes/MediaPicker/MediaPicker_filled.jsx
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/SelectorTypes/MediaPicker/MediaPicker_filled.spec.jsx

fix BACKLOG-10212 and BACKLOG-10213

BACKLOG-10212 : encode JCR path when used as URL.

---

src/javascript/DesignSystem/DatePicker/DatePicker.style.js
src/javascript/DesignSystem/DatePicker/TimeSelector/TimeSelector.jsx

Fix Font size, border radius and focus outline

BACKLOG-10401 : Fix Font size, border radius and focus outline

---

package.json
pom.xml
src/javascript/EditPanelContainer/EditPanel/EditPanel.jsx
src/javascript/EditPanelContainer/EditPanelContainer.jsx
yarn.lock

- Added language switcher to content-editor (doesn't do anything on language change yet)
- Upgraded dx-commons-webpack to version 1.1.1-SNAPSHOT

BACKLOG-10540 Integrate LanguageSwitcher in content-editor

---

src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/SelectorTypes/Checkbox/Checkbox.jsx
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/SelectorTypes/ChoiceList/ChoiceList.jsx

BACKLOG-10095 fix issue of action buttons when field is focused

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorForm.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormField.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSet.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldTarget.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormSection.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/StaticFormDefinitionRegistry.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/StaticFormFieldSetRegistry.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/resources/META-INF/jahia-content-editor-forms/forms/default.json
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetFieldTest.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetTest.java

Implemented BACKLOG-10726 & BACKLOG-10750

Backlog 9811 and 10007 mixin management

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

In this commit we make sure that we generate separate field sets for each non-dynamic (non-extend) mixin and super type that the primary node type is associated with.

BACKLOG-10751 Fix non dynamic field sets

---

src/javascript/DesignSystem/Picker/Picker.jsx
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/MultipleField.jsx
src/javascript/EditPanelContainer/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.jsx

* Style of reference picker
* Style of CKEditor
* Boolean multiple field with false value

BACKLOG-11067 fix issues

---

src/javascript/EditPanel/FormDefinitions/FormData.adapter.js
src/javascript/EditPanel/FormDefinitions/FormData.adapter.spec.js
src/javascript/NodeData/NodeData.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-11438

BACKLOG-11438: Add primaryNodeType to full content type detail info

---

src/javascript/DesignSystem/MultipleInput/MultipleInput.jsx
src/javascript/DesignSystem/MultipleInput/components/Control.jsx

BACKLOG-11358 style multiple input

---

src/javascript/DesignSystem/MultipleInput/components/Control.jsx
src/javascript/DesignSystem/Picker/Picker.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx

BACKLOG-11409: fix cursors on readonly

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/index.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/Validation/validation.utils.js
src/javascript/Validation/validation.utils.spec.js
src/main/resources/META-INF/jahia-content-editor-forms/fieldsets/jmix_keywords.json
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11296

BACKLOG-11296: Enter CE to the world of beta :tada: :tada: :tada:

---

src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/definitions/GqlNodeTypeTreeEntry.java
src/main/java/org/jahia/modules/contenteditor/utils/ContentEditorUtils.java
src/main/java/org/jahia/modules/contenteditor/utils/NodeTypeTreeEntry.java
src/test/java/org/jahia/modules/contenteditor/utils/ContentEditorUtilsTest.java

https://jira.jahia.org/browse/BACKLOG-11500

BACKLOG-11500 : order types tree entries alphabetically

---

src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/java/org/jahia/modules/contenteditor/utils/ContentEditorUtilsTest.java

https://jira.jahia.org/browse/BACKLOG-11495

BACKLOG-11495 : unload test resource

---

src/test/java/org/jahia/modules/contenteditor/utils/ContentEditorUtilsTest.java
src/test/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/BACKLOG-11500 

BACKLOG-11500 : improve test on disambiguateLabels

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/ImageListQuery/ImageListQuery.jsx

BACKLOG-11382 register refetch of ImageList in global callback object

---

src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.spec.js
src/javascript/Edit/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.actions.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11385

BACKLOG-11385: update the design of upload button

---

src/javascript/DesignSystem/ContentTable/ContentTable.jsx
src/javascript/DesignSystem/ImageList/ImageList.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerEmpty/ContentPickerEmpty.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerFilled/ContentPickerFilled.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerFilled/ContentPickerFilled.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.container.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerEmpty/MediaPickerEmpty.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerFilled/MediaPickerFilled.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerFilled/MediaPickerFilled.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.actions.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

BACKLOG-10940 style pickers

---

src/javascript/Create/CreateNewContentAction/CreateNewContent.gql-queries.js
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js
src/javascript/Create/CreateNewContentAction/withApolloAction.jsx
src/javascript/Create/index.js
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/definitions/GqlNodeTypeTreeEntry.java
src/main/java/org/jahia/modules/contenteditor/utils/ContentEditorUtils.java
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11508

BACKLOG-11508 : set init for create action

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.actions.js

https://jira.jahia.org/browse/BACKLOG-11551

BACKLOG-11551: fix file upload duplication entry in CMM

---

src/javascript/Create/CreateNewContentAction/createNewContent.utils.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js

https://jira.jahia.org/browse/BACKLOG-11558

BACKLOG-11558: Add unit test for creatNewContentUtils

---

src/javascript/DesignSystem/ImageList/ImageList.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerDialog.jsx

https://jira.jahia.org/browse/BACKLOG-11548

BACKLOG-11548: fix picker select button

---

src/javascript/Create/CreateNewContentAction/CreateNewContent.gql-queries.js
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utils.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js

https://jira.jahia.org/browse/BACKLOG-11557

Flatten node types

---

src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.utils.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js

https://jira.jahia.org/browse/BACKLOG-11557

BACKLOG-11557: add the ability to select orphan nodetype

---

src/javascript/Create/CreateNewContentAction/CreateNewContent.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-11579

BACKLOG-11579 : fix create button in nodetype selector

---

src/javascript/Create/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11574

BACKLOG-11574: change label + icon of create button

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-11508

BACKLOG-11572 : fix create button display in top bar

---

src/javascript/Create/CreateForm/create.request.js
src/javascript/Edit/Edit.jsx
src/javascript/Edit/save/save.request.js
src/javascript/EditPanel/EditPanel.utils.js
src/javascript/EditPanel/EditPanel.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-11584

BACKLOG-11584: filter not modified values before mutate them

---

src/javascript/DesignSystem/DatePicker/TimeSelector/TimeSelector.jsx

Date time picker pointer

---

src/javascript/Validation/validation.js
src/javascript/Validation/validation.spec.js

BACKLOG-11628: fix validation when there is no constraint

---

src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/Validation/validation.utils.js
src/javascript/Validation/validation.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-11676

BACKLOG-11676: Validate Form manually when submitting form - hic !

---

jest.config.js
package.json
src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx
src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.md
src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.spec.js
src/javascript/DesignSystem/DropdownTreeSelect/checked.svg
src/javascript/DesignSystem/DropdownTreeSelect/close.svg
src/javascript/DesignSystem/DropdownTreeSelect/unchecked.svg
yarn.lock

https://jira.jahia.org/browse/BACKLOG-11733

BACKLOG-11733: Add dropdown tree select component to CE design system

---

package.json
src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx
src/javascript/DesignSystem/DropdownTreeSelect/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/SelectorTypes.js
src/main/resources/META-INF/jahia-content-editor-forms/fieldsets/jmix_categorized.json
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-11734

BACKLOG-11734: Add category selectorTypes

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx
src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/category.adapter.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/category.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/catergory.adapter.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerFilled/MediaPickerFilled.jsx

https://jira.jahia.org/browse/BACKLOG-11737

BACKLOG-11737: Get categories for the category selector types

---

src/javascript/Validation/validation.js
src/javascript/Validation/validation.spec.js

https://jira.jahia.org/browse/BACKLOG-11676

BACKLOG-11676: fix pattern validator for multiple not mandatory

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx

https://jira.jahia.org/browse/BACKLOG-11735

BACKLOG-11735: handle category selector type save

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.utils.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.utils.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11839

BACKLOG-11839 : add all site in site switcher

---

src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Search/FolderDisplayer.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Search/FolderDisplayer.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Search/FolderName.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Search/Search.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Search/Search.spec.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-11744

BACKLOG-11744: Add a search input in pickers

---

src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx

https://jira.jahia.org/browse/BACKLOG-11839

BACKLOG-11839 : fix all sites selection

---

src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentPickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/MediaPickerDialog.jsx

https://jira.jahia.org/browse/BACKLOG-11858

BACKLOG-11858 : unify site switcher callback

---

src/javascript/Create/CreateNewContentAction/CreateNewContent.gql-queries.js
src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.utils.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js
src/javascript/Create/index.js

https://jira.jahia.org/browse/QA-12416

QA-12416 : add restriction on create content action

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-11979

BACKLOG-11979: avoid display in tree while filtering categories

---

src/javascript/Edit/engineTabs/engineTabs.utils.js

https://jira.jahia.org/browse/BACKLOG-11935

BACKLOG-11935 : fix display of tabs from custom configuration

---

src/javascript/Edit/engineTabs/engineTabs.utils.js

https://jira.jahia.org/browse/BACKLOG-11935

BACKLOG-11935 : restore non supported tabs

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/ImageListQuery/ImageListQuery.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.configs.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Search/search.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-12003

BACKLOG-12003 : improve queries in pickers

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx

https://jira.jahia.org/browse/BACKLOG-11939

BACKLOG-11939 : fix button issue in image picker

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/Section.jsx

https://jira.jahia.org/browse/BACKLOG-11576

BACKLOG-11576 : add space between section in CE

---

src/javascript/DesignSystem/ContentTable/ContentTable.jsx
src/javascript/DesignSystem/ContentTable/ContentTable.spec.js
src/javascript/DesignSystem/PickerDialog/PickerDialog.jsx
src/javascript/DesignSystem/PickerDialog/PickerDialog.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/NavigateInto.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx

Picker navigate into

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/ContentTable/ContentTable.spec.jsx

BACKLOG-11962: Display date in picker according to user lang preference

---

package.json
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-12053

BACKLOG-12053 : Add plugin and rename picker.jsx file

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/LeftPanel.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/MainPanel.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.spec.jsx

Add test to picker dialog

---

src/javascript/DesignSystem/Picker/picker.story.jsx

Restore picker story

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx

https://jira.jahia.org/browse/QA-12535

QA-12535 : use onSelectSite function

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-12038

BACKLOG-12038 : modify dropdownTreeSelect style

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/LeftPanel.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/MainPanel.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx

https://jira.jahia.org/browse/BACKLOG-10321

BACKLOG-10321 : enable select button only when element is selected

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.jsx

https://jira.jahia.org/browse/BACKLOG-12058

BACKLOG-12058: clean and fix code after refactoring react i18next

---

src/javascript/Edit/Edit.jsx
src/javascript/Edit/publish/publish.action.jsx
src/javascript/Edit/publish/publish.action.spec.js
src/javascript/Edit/startWorkflow/startWorkflow.action.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.spec.js
src/javascript/EditPanel/FormDefinitions/FormData.adapter.js
src/javascript/EditPanel/FormDefinitions/FormData.adapter.spec.js
src/javascript/NodeData/NodeData.gql-queries.js
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/DXGraphQLContentEditorProvider.java
src/main/java/org/jahia/modules/contenteditor/graphql/extensions/JCRNodeContentEditorExtensions.java

https://jira.jahia.org/browse/BACKLOG-12095

BACKLOG-12095 : allow lock owner to edit an edit locked content

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/MainPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12104

BACKLOG-12104 : make picker content scrollable

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-12038

BACKLOG-12038 : hide dropdown content when disabled

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/useDebounce.js

Debounce search

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-12038

BACKLOG-12038 : hide search field when disabled

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx

https://jira.jahia.org/browse/BACKLOG-11930:

BACKLOG-11930: Fix search of category selectorTypes

---

package.json
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerContainer.jsx
src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12125

BACKLOG-12125 : Renamed CMM

---

src/javascript/EditPanel/EditPanel.jsx
src/javascript/Lock/LockInfo.badge.jsx
src/javascript/Lock/LockInfo.badge.spec.js
src/javascript/NodeData/NodeData.gql-queries.js
src/javascript/PublicationInfo/PublicationInfo.badge.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12152

Backlog 12152 add lock info badges

---

src/javascript/NodeData/NodeData.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-12151

BACKLOG-12151 : add owner of a lock in node data query

---

src/javascript/DesignSystem/ContentTable/ContentTable.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/CountDisplayer.jsx

https://jira.jahia.org/browse/BACKLOG-12128

BACKLOG-12128 : add selectors for infinite scroll test

---

src/javascript/Edit/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx

https://jira.jahia.org/browse/BACKLOG-12238

BACKLOG-12238 : fix pickers

---

src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12157

BACKLOG-12157 : fix routes

---

src/javascript/Edit/engineTabs/engineTabs.utils.js

https://jira.jahia.org/browse/BACKLOG-11820

BACKLOG-11820 : fix actions

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/Thumbnail/Thumbnail.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/BACKLOG-12233

BACKLOG-12233 : fix pickers actions

---

src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/FormDefinitions/FormDefinitions.js

https://jira.jahia.org/browse/BACKLOG-12257

BACKLOG-12257 : fix back button

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-11952
Upgrade version and Jahia dependencies due to Spring OSGI feature

BACKLOG-11952: Update version

---

src/javascript/register.jsx

BACKLOG-12184 : Add root component in registry

---

src/javascript/Create/Create.container.jsx
src/javascript/Create/Create.container.spec.jsx
src/javascript/Edit/Edit.container.jsx
src/javascript/Edit/Edit.container.spec.js

https://jira.jahia.org/browse/BACKLOG-12335

BACKLOG-12335 : use correct redux state to get the path

---

src/javascript/ContentManager.redux-actions.js
src/javascript/EditPanel/EditPanelContent/EditPanelContent.jsx

https://jira.jahia.org/browse/BACKLOG-12335

BACKLOG-12335 : fix : preview and back button

---

src/javascript/DesignSystem/MultipleInput/MultipleInput.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.spec.js

https://jira.jahia.org/browse/BACKLOG-12304

BACKLOG-12304 : adapt component to use tag suggestions query

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.jsx

https://jira.jahia.org/browse/BACKLOG-12304

BACKLOG-12304 : disable cache on tag suggestion

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/FormDefinitions/FormData.proptypes.js
src/javascript/NodeData/NodeData.gql-queries.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12454

BACKLOG-11343 : add component to show section with children nodes

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenContainer/ChildrenContainer.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenContainer/ChildrenContainer.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenContainer/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.jsx
src/javascript/NodeData/NodeData.gql-queries.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12455

BACKLOG-12455 : use picker component to show children nodes

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12413

BACKLOG-12413 : make modal display menu

---

src/javascript/DesignSystem/Picker/index.js
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.jsx
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.md
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.spec.jsx
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.story.jsx
src/javascript/DesignSystem/ReferenceCard/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenContainer/ChildrenContainer.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerContainer.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerContainer.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12499

BACKLOG-12499 : rename picker input component to reference card

---

src/javascript/Edit/Edit.actions.js
src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.action.spec.jsx
src/javascript/EditPanel/EditPanel.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12536

BACKLOG-12536 : add copy language action in the 3 dots menu

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.utils.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.utils.spec.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12580

BACKLOG-12580: export and add test to rich text utilities functions

---

src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.utils.js
src/javascript/Edit/copyLanguage/copyLanguage.utils.spec.js
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.spec.jsx
src/javascript/EditPanel/CopyLanguageDialog/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12537

BACKLOG-12537 : add the modal to allows to copy values from a language

---

package.json
src/javascript/ContentEditor.register.jsx
src/javascript/ContentEditor.register.spec.js
src/javascript/index.js
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-12161 

BACKLOG-12161 : App shell , move registration in promise

---

src/javascript/Create/CreateForm/createForm.gql-queries.js
src/javascript/FormDefinitions/FormData.adapter.js
src/javascript/FormDefinitions/FormData.adapter.spec.js

https://jira.jahia.org/browse/BACKLOG-12594

BACKLOG-12594 : do not fill create content with parent data

---

webpack.config.js

https://jira.jahia.org/browse/BACKLOG-12621

BACKLOG-12621 : fix webpack conflicts

---

src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js

https://jira.jahia.org/browse/BACKLOG-12623

BACKLOG-12623 : fix content type selector for no type defined

---

pom.xml
src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.utils.js
src/javascript/Edit/copyLanguage/copyLanguage.utils.spec.js
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12625

Backlog 12625 styling copy language modal

---

pom.xml
src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.utils.js
src/javascript/Edit/copyLanguage/copyLanguage.utils.spec.js
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12538

BACKLOG-12538 : fill field with another language values

---

src/javascript/Api/ContentEditor.api.jsx

BACKLOG-12630 remove the hardcoded header in CE standalone

---

src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/ContentPreviewMemoWrapper.jsx

https://jira.jahia.org/browse/BACKLOG-12511

BACKLOG-12511 : fix preview refresh

---

src/javascript/Create/Create.actions.js

https://jira.jahia.org/browse/BACKLOG-12330

BACKLOG-12330 : add the new target on create action

---

package.json
yarn.lock

BACKLOG-12696 : remove husky

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/index.js

https://jira.jahia.org/browse/BACKLOG-12708

BACKLOG-12708 : fix picker selection

---

src/javascript/Edit/Edit.jsx
src/javascript/Edit/engineTabs/engineTabs.utils.js
src/javascript/Edit/engineTabs/useRegisterEngineTabActions.js
src/javascript/Edit/engineTabs/useRegisterEngineTabActions.spec.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.scss
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.scss
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12650

BACKLOG-12650 : add template layout for advanced options tab

---

src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.actions.js
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.scss
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/GoToOption.action.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12652

Backlog 12652 adapt detail panel

---

src/javascript/Edit/engineTabs/openEngineTabs.action.jsx
src/javascript/Edit/engineTabs/useRegisterEngineTabActions.js
src/javascript/Edit/engineTabs/useRegisterEngineTabActions.spec.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.scss
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12653

BACKLOG-12653 : finalize action handling for advanced option tab

---

src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12781

BACKLOG-12781 : use uuid instead of path to get the form data

---

src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.jsx

https://jira.jahia.org/browse/BACKLOG-12707

BACKLOG-12707 : use component props of layout module component

---

src/javascript/Edit/Edit.jsx
src/javascript/Edit/engineTabs/useRegisterEngineTabActions.js
src/javascript/EditPanel/AdvancedOptions/AdvancedOptions.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx

https://jira.jahia.org/browse/BACKLOG-12783

BACKLOG-12783 : refresh correcty detail panel

---

src/javascript/EditPanel/EditPanelContent/EditPanelContent.jsx
src/javascript/EditPanel/EditPanelContent/PreviewContainer/PreviewContainer.jsx
src/javascript/EditPanel/EditPanelContent/PreviewContainer/PreviewContainer.scss
src/javascript/EditPanel/EditPanelContent/PreviewContainer/PreviewContainer.spec.js

https://jira.jahia.org/browse/BACKLOG-12810

BACKLOG-12810 : refacto detail panel to remove preview button

---

src/javascript/Create/Create.actions.js
src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.action.spec.jsx
src/javascript/Edit/Edit.actions.js
src/javascript/Edit/EditContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-12736

BACKLOG-12736 : add permission check on create / edit actions

---

src/javascript/Edit/Edit.jsx
src/javascript/Edit/save/save.request.js
src/javascript/Edit/unpublish/unpublish.request.js
src/javascript/PublicationInfo/PublicationInfo.context.js
src/javascript/PublicationInfo/PublicationInfo.gql-queries.js
src/javascript/PublicationInfo/PublicationInfo.jsx

https://jira.jahia.org/browse/BACKLOG-12781

BACKLOG-12781 : use id instead of path in graphql request

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-12859

BACKLOG-12859 : Fix menu loading

---

src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.utils.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.utits.js

https://jira.jahia.org/browse/BACKLOG-12886

BACKLOG-12886 : fix nodetype selection

---

src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/EditPanel.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.spec.js
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.scss
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.spec.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12844

BACKLOG-12844 : add wip action and wip modal component

---

src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12882

Backlog 12882 add link to academy

---

src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12920

BACKLOG-12920: Move "Wip" and "copy from..." actions to 3 dots menu

---

src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.scss
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.spec.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12848

Backlog 12848 adapt wip modal

---

src/javascript/Edit/Edit.adapter.js
src/javascript/Edit/Edit.adapter.spec.js
src/javascript/Edit/save/save.gql-mutation.js
src/javascript/Edit/save/save.request.js

System name save during edition of the node in content editor, covered by tests

BACKLOG-12898: rename node if system name is changed during edition

---

src/javascript/EditPanel/EditPanel.jsx
src/javascript/EditPanel/EditPanel.scss
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.spec.jsx
src/javascript/EditPanel/WorkInProgress/Chip/WipInfo.Chip.jsx
src/javascript/EditPanel/WorkInProgress/Chip/WipInfo.Chip.spec.js
src/javascript/EditPanel/WorkInProgress/WorkInProgress.utils.js
src/javascript/EditPanel/WorkInProgress/WorkInProgress.utils.spec.js
src/javascript/NodeData/NodeData.gql-queries.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12850

BACKLOG-12850 : add wip chip to the header and i18n fields

---

src/javascript/EditPanel/WorkInProgress/WorkInProgress.utils.js

https://jira.jahia.org/browse/BACKLOG-12850

BACKLOG-12850 : add control to check if wip info exists

---

src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-12921

BACKLOG-12921 : add data sel role for selenium

---

src/javascript/Create/Create.actions.js
src/javascript/DesignSystem/ContentLayout/ContentHeader/ContentHeader.scss
src/javascript/DesignSystem/ContentLayout/MainLayout/MainLayout.jsx
src/javascript/DesignSystem/ContentLayout/MainLayout/MainLayout.scss
src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/header/LowerSection.scss

https://jira.jahia.org/browse/BACKLOG-12940
This PR change the main layout margin, and add a box-shaddow bellow the header.
Only manual testing
I have considered the following implications of my change: 
No need for documentation here

Layout fixes

---

src/javascript/Create/Create.adapter.js
src/javascript/Create/CreateForm/createForm.gql-mutation.js
src/javascript/Create/CreateForm/createForm.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-13010

BACKLOG-13010 : use dedicate wip mutation for creation

---

src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.spec.jsx

https://jira.jahia.org/browse/BACKLOG-12978
- set WIP a current language when enabled
https://jira.jahia.org/browse/BACKLOG-12974
- show WIP options only when enabled
Testing
- Unit tested
- Integration test required

]BACKLOG-12978 - BACKLOG-12974 : improve WIP dialog

---

src/javascript/Create/Create.adapter.js

https://jira.jahia.org/browse/BACKLOG-13010
Fix create action

BACKLOG-13010 : rebuild wipInfo object properly

---

package.json
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.jsx
src/javascript/EditPanel/WorkInProgress/WorkInProgressDialog/WorkInProgressDialog.spec.jsx
src/main/resources/jnt_globalSettings/js/globalSettings.contentEditor.jsp

https://jira.jahia.org/browse/BACKLOG-12979

BACKLOG-12979 : update academy link

---

src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12976

BACKLOG-12976 : WIP - change label for single language site

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx

https://jira.jahia.org/browse/BACKLOG-12850

BACKLOG-12850 : fix the displaying of the wip badges on field

---

src/javascript/ContentEditor.constants.js
src/javascript/Create/Create.adapter.js
src/javascript/Edit/Edit.adapter.js
src/javascript/utils/helper.js
src/javascript/utils/helper.spec.js

system name encoding for reserved JCR characters
covered by react tests

BACKLOG-12967: system name encoding JCR reserverd characters

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-12892

BACKLOG-12892 : fix url icons dropdown tree select

---

src/javascript/EditPanel/header/UpperSection.jsx
src/javascript/EditPanel/header/UpperSection.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-13035

BACKLOG-13035 : add unsaved info chip when a content is modified

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx

https://jira.jahia.org/browse/BACKLOG-13044
Put the ordering section after content section

BACKLOG-13044 put the ordering section after content section

---

src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss

https://jira.jahia.org/browse/BACKLOG-12891
Improve style CopyLanguageDialog

BACKLOG-12891 improve style CopyLanguageDialog

---

src/javascript/Api/ContentEditor.api.jsx

https://jira.jahia.org/browse/BACKLOG-12779

BACKLOG-12779 : increase zindex value of ce dialog

---

src/javascript/ContentEditorHistory/ContentEditorHistory.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-13038
Covered by integration test

BACKLOG-13038 : fix and use only store location for back button

---

src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-13072

BACKLOG-13072 : add icon and set color on unsaved chip

---

src/javascript/DesignSystem/ReferenceCard/ReferenceCard.jsx
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenOrderField/DragDrop/DraggableReference.jsx

https://jira.jahia.org/browse/BACKLOG-13050
Update design of ReferenceCard

BACKLOG-13050 update design of ReferenceCard

---

src/javascript/Edit/Edit.actions.js
src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.action.spec.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss

https://jira.jahia.org/browse/BACKLOG-13069
Update copy language action

BACKLOG-13069 update copy language action

---

src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-13078

BACKLOG-13078 : change title style and limit text size

---

src/javascript/Create/Create.adapter.js
src/javascript/FormDefinitions/FormData.adapter.js
src/javascript/FormDefinitions/FormData.adapter.spec.js

https://jira.jahia.org/browse/BACKLOG-11785

BACKLOG-11785 : disable modification on contents and files node

---

.github/workflows/nodejs.yml
src/javascript/ContentEditor.context.js
src/javascript/Create/Create.adapter.js
src/javascript/Edit/Edit.adapter.js
src/javascript/EditPanel/EditPanel.jsx
src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-13109

BACKLOG-13109 : display the good node type

---

.github/workflows/nodejs.yml
package.json
src/javascript/EditPanel/header/LowerSection.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12940
Fix button and tabs displaying + add build step in CI

Fix styles

---

src/javascript/Create/Create.actions.js
src/javascript/Edit/Edit.actions.js
src/javascript/EditPanel/header/ActionsButtons.jsx
src/javascript/EditPanel/header/ActionsButtons.scss
src/javascript/EditPanel/header/UpperSection.jsx
src/javascript/EditPanel/header/UpperSection.scss

https://jira.jahia.org/browse/BACKLOG-13088
Fix pastille position and split save-action from publish actions

BACKLOG-13088: fix pastille postion

---

src/javascript/FormDefinitions/FormData.adapter.js

https://jira.jahia.org/browse/BACKLOG-11785

BACKLOG-11785 : change regexp to match exact phrase

---

src/javascript/ContentEditor.register.jsx

https://jira.jahia.org/browse/BACKLOG-13026
Renamed main route target to have consistent and significant naming. Avoid confusion with nav targets.

BACKLOG-13026: renamed route

---

package-lock.json
src/javascript/ContentEditorId.context.js
src/javascript/EditPanel/EditPanel.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-13075

BACKLOG-13075 : fix lock removing when leave ce

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/MultipleSelect/actions/selectAll.action.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/MultipleSelect/actions/selectAll.action.spec.js
src/javascript/EditPanel/header/UpperSection.scss

https://jira.jahia.org/browse/BACKLOG-12733

BACKLOG-12733: Fix the select all action of multiple choice list

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-13169

BACKLOG-13169 : display mixins related to a virtualsite node

---

src/javascript/ContentEditor.context.js
src/javascript/EditPanel/EditPanel.jsx
src/javascript/FormDefinitions/FormDefinitions.js

https://jira.jahia.org/browse/BACKLOG-13123

BACKLOG-13123 : handle close publish panel to refresh content editor

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js

https://jira.jahia.org/browse/BACKLOG-13192

BACKLOG-13192 : disable save button once clicked

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/ContentEditor.constants.js
src/javascript/Create/Create.jsx
src/javascript/Edit/Edit.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-13135
Refresh jExperience entry when exiting Content Editor using back button
Unit tests will be covered by:
https://jira.jahia.org/browse/BACKLOG-13205

BACKLOG-13135 : trigger events properly when exiting from back button

---

src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/ContentPreviewMemoWrapper.spec.js
src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/Preview.utils.js
src/javascript/EditPanel/EditPanelContent/PreviewContainer/Preview/Preview.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-13203
Fixes preview
Covered by unit tests

BACKLOG-13203 : fix preview to display staging working

---

LICENSE.txt
pom.xml
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorForm.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormException.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormField.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSet.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldTarget.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldValue.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldValueConstraint.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormProperty.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormSection.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormSectionDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/StaticDefinitionsRegistry.java
src/main/java/org/jahia/modules/contenteditor/graphql/DXGraphQLContentEditorProvider.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlUtils.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/definitions/GqlNodeTypeTreeEntry.java
src/main/java/org/jahia/modules/contenteditor/graphql/extensions/QueryExtensions.java
src/main/java/org/jahia/modules/contenteditor/render/PreviewWrapperFilter.java
src/main/java/org/jahia/modules/contenteditor/utils/ContentEditorUtils.java
src/test/java/org/jahia/modules/DummyBundle.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetFieldTest.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetTest.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/java/org/jahia/modules/contenteditor/utils/ContentEditorUtilsTest.java

Backlog-13160 - Update copyright

---

src/javascript/Create/Create.jsx
src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/header/UpperSection.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-13209
make back button work again
Not covered with unit test (see https://jira.jahia.org/browse/BACKLOG-13205)

BACKLOG-13209 : fix back action (still missing unit test, BACKLOG-13205)

---

src/javascript/EditPanel/EditPanel.actions.js
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/DMF-3817

DMF-3817 : Allows to add tabs action

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/field.utils.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/field.utils.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-13043
Add error message for maxLenght

BACKLOG-13043: Add error message for maxLenght

---

src/javascript/Api/ContentEditor.api.jsx

https://jira.jahia.org/browse/BACKLOG-12588
Previuos fix was not working on Firefox and was cuasing issues with advanced options in content editor

BACKLOG-12588: disable focus management by material

---

src/javascript/EditPanel/EditPanel.actions.js
src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/DMF-3818

Dmf 3818 add new jexperience action

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-13160

BACKLOG-13160 : Updated version

---

src/javascript/Create/Create.jsx

https://jira.jahia.org/browse/QA-12745
fix language switching on created content 
Covered by integration test only

QA-12745 : fix language switching on created content

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSet.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetBuilder.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetTest.java

- Added unit test for this case
- Fix problem
https://jira.jahia.org/browse/BACKLOG-13278

BACKLOG-13278 Fix remove field set override

---

src/javascript/NodeData/NodeData.gql-queries.js

BACKLOG-13065 consider wemnt:pageVariant as page

---

src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-13302
Add Selenium selector
Used by integration test

BACKLOG-13302 : add selenium selector to title

---

src/javascript/ContentEditor.context.js
src/javascript/ContentEditor.jsx
src/javascript/Edit/engineTabs/ApolloCacheFlushOnGWTSave.jsx

https://jira.jahia.org/browse/BACKLOG-13179

BACKLOG-13179 : refresh data when there is a modification form gwt

---

src/javascript/ContentEditor.constants.js
src/javascript/Edit/Edit.adapter.js
src/javascript/Edit/Edit.adapter.spec.js
src/javascript/Edit/save/save.gql-mutation.js
src/javascript/Edit/save/save.request.spec.js
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.spec.js

https://jira.jahia.org/browse/BACKLOG-13169

BACKLOG-13169 : remove wip info when modifying a site node

---

src/javascript/Edit/save/save.gql-mutation.js

https://jira.jahia.org/browse/BACKLOG-13216

BACKLOG-13216 fix wip regression on mixin update

---

src/javascript/utils/helper.js
src/javascript/utils/helper.spec.js

https://jira.jahia.org/browse/BACKLOG-13082

BACKLOG-13082 : remove / character in the system name and replace *

---

src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx

https://jira.jahia.org/browse/BACKLOG-13322
Take into consideration the parameter writePermission to avoid the error of the GraphQL query

BACKLOG-13322 : consideration of the write permission parameter

---

src/javascript/NodeData/NodeData.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-13325

BACKLOG-13325 : take into consideration write permission

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/PickerDialog.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-12252

BACKLOG-12252 : renaming of editModeAccess permission

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/FieldSet.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/FieldSet.spec.jsx

https://jira.jahia.org/browse/BACKLOG-13323

BACKLOG-13323 : consider write permission only in edit mode

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/ContentPicker/index.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/index.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/MediaPicker/index.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/actions/openInTab.action.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/actions/openInTab.action.spec.js

https://jira.jahia.org/browse/BACKLOG-13174
Now open in new tab action for reference field is working properly. 
Covered with unit tests.

BACKLOG-13174 : fix open in new tab action for reference.

---

src/javascript/EditPanel/EditPanelContent/Preview/PreviewViewers/IframeViewer/IframeViewer.jsx

https://jira.jahia.org/browse/BACKLOG-13360
fix preview in firefox

BACKLOG-13360: fix preview in firefox

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx

https://jira.jahia.org/browse/QA-12774

QA-12774 : hide content list section in create mode

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.utils.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/Picker.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-13370
Fix site switcher 
Covered by unit tests

BACKLOG-13370 : fix site switcher

---

src/javascript/ContentEditor.constants.js
src/javascript/EditPanel/EditPanel.actions.js
src/javascript/EditPanel/tabbar/tabbar.action.jsx
src/javascript/EditPanel/tabbar/tabbar.action.spec.jsx
src/main/import/permissions.xml
src/main/import/roles.xml

https://jira.jahia.org/browse/BACKLOG-13201

BACKLOG-13201 add permission for advanced options tab

---

src/javascript/utils/helper.js
src/javascript/utils/helper.spec.js

https://jira.jahia.org/browse/BACKLOG-13082

BACKLOG-13082 : replace / and : character in system name

---

src/javascript/DesignSystem/ContentTable/ContentTable.jsx
src/javascript/DesignSystem/ContentTable/ContentTable.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/List/List.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/content.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Picker/PickerDialog/Views/useDialogPickerContent.jsx

https://jira.jahia.org/browse/QA-12730
This allows to display non selectable items in pickers. Link picker use this configuration. 
Covered with unit test.

QA-12730 : display non selectable content in pickers

---

src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/Edit/save/save.request.js

https://jira.jahia.org/browse/BACKLOG-13383

BACKLOG-13383 : flush cache on save

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-13212
Disabled content creation under menu labels

Disabled content creation under menu labels

---

src/javascript/Create/CreateForm/create.request.js

https://jira.jahia.org/browse/BACKLOG-13334
fix missing system name when creating content

BACKLOG-13334 : fix content creation when system name not editable

---

src/javascript/EditPanel/EditPanelContent/Preview/PreviewViewers/IframeViewer/IframeViewer.jsx

https://jira.jahia.org/browse/BACKLOG-13565
Fix flickering by reducing dependencies to data  (which is the only object really changing after save). Fix zoom or attempt to zoom after the catch if any error occur in the preview (mostly during assets loads, as in digitall homepage)

BACKLOG-13565: Fix flickering by reducing dependencies to data

---

src/javascript/EditPanel/EditPanelContent/Preview/PreviewViewers/IframeViewer/IframViewer.spec.js
src/javascript/EditPanel/EditPanelContent/Preview/PreviewViewers/IframeViewer/IframeViewer.jsx

https://jira.jahia.org/browse/BACKLOG-13568
fix preview for contents that cannot be displayed in a page.

BACKLOG-13568 : fix preview

---

pom.xml

Update content editor signature

---

src/javascript/FormDefinitions/FormDefinitions.js

https://jira.jahia.org/browse/BACKLOG-13584

BACKLOG-13584 : use network only to get form definition

---

src/javascript/FormDefinitions/FormData.adapter.js
src/javascript/FormDefinitions/FormData.adapter.spec.js

https://jira.jahia.org/browse/BACKLOG-13624

BACKLOG-13624 : check write permission for the system name

---

src/javascript/EditPanel/tabbar/tabbar.action.jsx
src/javascript/EditPanel/tabbar/tabbar.action.spec.jsx
src/main/import/roles.xml

https://jira.jahia.org/browse/QA-12930

QA-12930 : fix advanced tab permission check

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx

https://jira.jahia.org/browse/BACKLOG-13854

BACKLOG-13854 : fix choicelist value resolution.

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/RichText/RichText.test.jsx

https://jira.jahia.org/browse/BACKLOG-13862

BACKLOG-13862 call onChange function

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Checkbox/Checkbox.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Checkbox/Checkbox.spec.js

https://jira.jahia.org/browse/BACKLOG-13856

BACKLOG-13856: call onchange method in checkbox selector type

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Tag/Tag.spec.js

https://jira.jahia.org/browse/BACKLOG-13861

BACKLOG-13861: add on change call on tag selector type

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/DateTimePicker/DateTimePicker.spec.js

https://jira.jahia.org/browse/BACKLOG-13864

BACKLOG-13864: call onChange for date time picker

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Text/Text.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Text/Text.test.jsx

https://jira.jahia.org/browse/BACKLOG-13857

BACKLOG-13857 : add onChange on text selector

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/Category.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/category.adapter.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/category.adapter.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/Category/category.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/TextArea/TextArea.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/TextArea/TextArea.spec.js

https://jira.jahia.org/browse/BACKLOG-13859
Covered with unit tests and selenium tests

BACKLOG-13859 : add onChange on Textarea and categories selector

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-13108

Backlog 13108 unescape html characters

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/jahia-content-editor-forms/overrides/fieldSets/jnt_simple_rank_override_field_value_constraints.json

https://jira.jahia.org/browse/BACKLOG-13840

BACKLOG-13840 add fieldConstraints to GraphQL api

---

src/javascript/AddMixin.register.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/SelectorTypes/ChoiceList/MultipleSelect/MultipleSelect.jsx

https://jira.jahia.org/browse/BACKLOG-13927

BACKLOG-13927: handle multiple choicelist addmixin method

---

src/main/resources/jnt_globalSettings/js/globalSettings.contentEditor.jsp

https://jira.jahia.org/browse/QA-12950

QA-12950 : update academy wip link

---

src/javascript/ContentEditor.constants.js
src/javascript/ContentEditor.context.js
src/javascript/Edit/EditForm.gql-queries.js
src/javascript/Edit/save/save.request.js
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx

https://jira.jahia.org/browse/BACKLOG-13172

BACKLOG-13172 : filter displayed children

---

src/javascript/SelectorTypes/SelectorTypes.js
src/javascript/SelectorTypes/SelectorTypes.spec.js

https://jira.jahia.org/browse/QA-13003

QA-13003 adapt value fallback for text component

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/ContentEditor.redux.jsx

https://jira.jahia.org/browse/QA-12787

QA-12787 Refresh GWT and JContent on click back button

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/types/ContextEntryInput.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java

https://jira.jahia.org/browse/BACKLOG-14045

BACKLOG-14045 add support for depends properties

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/BACKLOG-14049

BACKLOG-14049 : consider extends mixin in content editor

---

src/javascript/ContentEditor.constants.js
src/javascript/EditPanel/EditPanel.actions.js
src/javascript/EditPanel/EditPanel.jsx
src/javascript/EditPanel/EditPanel.scss

https://jira.jahia.org/browse/QA-13016

QA-13016 : avoid save to be activated when switching to detail panel

---

src/javascript/Edit/EditForm.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx

https://jira.jahia.org/browse/QA-12772

QA-12772 : hide ordering section for site node

---

src/javascript/EditPanel/EditPanel.jsx

https://jira.jahia.org/browse/BACKLOG-14097

BACKLOG-14097 : fix scroll bar in content editor

---

src/javascript/Edit/publish/publish.request.js

https://jira.jahia.org/browse/BACKLOG-13079

BACKLOG-13079 set autoHideDuration to 3 seconds

---

src/javascript/ContentEditor.context.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.gql-queries.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.spec.jsx
src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx
src/javascript/SelectorTypes/SelectorTypes.js
src/javascript/SelectorTypes/SelectorTypes.onChange.js

https://jira.jahia.org/browse/BACKLOG-14046

BACKLOG-14046 integrate dependent properties in CE

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerCircleCIOnPR.yml

https://jira.jahia.org/browse/BACKLOG-13891

BACKLOG-13891 : enable circle ci

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/MultipleField.jsx

https://jira.jahia.org/browse/BACKLOG-14085

BACKLOG-14085 : fix multiple picker item display in Content Editor

---

src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.spec.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-14062
* Updated CreateNewContentDialog with moonstone buttons and updates tests as necessary

BACKLOG-14062 (Part 2): Updates CreateNewContentDialog with Moonstone Buttons

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-13891

fix circle ci configuration

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-14133

BACKLOG-14133: update dependencies to restore storybook

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentBreadcrumb.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.jsx

https://jira.jahia.org/browse/BACKLOG-14193

BACKLOG-14193 update style of breadcrumb separators

---

src/javascript/DesignSystem/Card/Card.jsx
src/javascript/DesignSystem/DatePicker/DatePicker.style.js
src/javascript/DesignSystem/MultipleInput/components/Control.jsx
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.jsx
src/javascript/DesignSystem/TextArea/TextArea.jsx
src/javascript/DesignSystem/TreeView/TreeView.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/MultipleField.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/MultipleField.spec.jsx
src/javascript/EditPanel/EditPanelDialogConfirmation/EditPanelDialogConfirmation.jsx
src/javascript/EditPanel/EditPanelDialogConfirmation/EditPanelDialogConfirmation.scss
src/javascript/EditPanel/EditPanelDialogConfirmation/EditPanelDialogConfirmation.spec.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.spec.jsx
src/javascript/Validation/SaveModal/SaveErrorModal.jsx
src/javascript/Validation/SaveModal/SaveErrorModal.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14062
* Change darker blue accent colour to Moonstone lighter blue accent colour for many components
* Changed Language Switcher in the header to Moonstone dropdown component
* More buttons changed to Moonstone buttons

BACKLOG-14062: Moonstone Colours, Language Switcher, Buttons

---

src/javascript/Create/Create.actions.js
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java

https://jira.jahia.org/browse/BACKLOG-14183

BACKLOG-14183: consider nodetypes from context to display action

---

src/javascript/ContentEditor.constants.js
src/javascript/FormDefinitions/FormData.adapter.js

https://jira.jahia.org/browse/BACKLOG-13301

BACKLOG-13301 move category system-name up in content section

---

src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx

https://jira.jahia.org/browse/BACKLOG-14062

BACKLOG-14062: Adds data-cm-role to fix automated test

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentBreadcrumb.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.test.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.jsx

https://jira.jahia.org/browse/BACKLOG-14188

BACKLOG-14188 manage mode when access CE from url

---

src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx

https://jira.jahia.org/browse/BACKLOG-14224

BACKLOG-14224 : fix reset of single field

---

src/javascript/SelectorTypes/Picker/Picker.configs.js
src/javascript/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/List/List.spec.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/content.gql-queries.js
src/javascript/SelectorTypes/Picker/PickerDialog/Views/useDialogPickerContent.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/useDialogPickerContent.spec.jsx

https://jira.jahia.org/browse/QA-13027

QA-13027: consider descendants to display content in picker

---

package.json
src/javascript/Api/ContentEditor.api.jsx
src/javascript/ContentEditor.redux.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentBreadcrumb.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.test.jsx
src/javascript/EditPanel/header/UpperSection.jsx
yarn.lock

* breadcrumb in category manager
* use CE dialog confirmation
https://jira.jahia.org/browse/BACKLOG-14186

BACKLOG-14186 handle special cases

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-14155

BACKLOG-14155 use session with locale to retrieve node

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx

https://jira.jahia.org/browse/BACKLOG-14244

BACKLOG-14244 handle categories redirect and back

---

package.json
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-14256

BACKLOG-14256 add timeStamp to the bundle file name

---

package.json
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-14273

BACKLOG-14273 allow pass buildTimeStamp parameter to webpack

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-14155

BACKLOG-14155 add fallback locale to the session

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.spec.jsx

https://jira.jahia.org/browse/BACKLOG-14246

BACKLOG-14246 use the same behaviour as jContent

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/BACKLOG-14289

BACKLOG-14289 : update the chip color for category selector

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.spec.jsx

https://jira.jahia.org/browse/BACKLOG-14298

BACKLOG-14298 adapt path for breadcrumb component

---

package.json
pom.xml

https://jira.jahia.org/browse/BACKLOG-14257

BACKLOG-14257 : bump content editor to 3.0.0

---

src/javascript/ContentEditor.redux.jsx
src/javascript/ContentEditorHistory/ContentEditorHistory.jsx
src/javascript/Edit/Edit.env.js
src/javascript/Edit/Edit.jsx
src/javascript/Edit/save/save.request.js
src/javascript/Edit/save/save.request.spec.js
src/javascript/JContent.redux-actions.js
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-13207

BAKLOG-13207 : update jcontent path when system name changed

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-14257

BACKLOG-14257 : update pom signature for 3.0.0-SNAPSHOT

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14294

BACKLOG-14294 rewrite resource bundles of WIP

---

src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js

https://jira.jahia.org/browse/BACKLOG-14318

BACKLOG-14318: disable field if dependent field is empty

---

pom.xml
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/BACKLOG-14316

BACKLOG-14316 support new name for templateMixin

---

package.json
src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-14290
* Updated left border of field to have moonstone warning support 60% opacity
* Updated error message text of field to have moonstone warning support 100% opacity

BACKLOG-14290: Validation Feedback Colours

---

src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js
src/javascript/SelectorTypes/ChoiceList/MultipleSelect/MultipleSelect.jsx
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx

https://jira.jahia.org/browse/BACKLOG-14318

BACKLOG-14318 : handle changes to correctly save the field values

---

src/javascript/DesignSystem/DatePickerInput/DatePickerInput.jsx
src/javascript/SelectorTypes/DateTimePicker/DateTimePicker.jsx

https://jira.jahia.org/browse/BACKLOG-13950

BACKLOG-13950 : fix date removal in multiple + fix proptypes check.

---

src/javascript/DesignSystem/MultipleInput/MultipleInput.jsx
src/javascript/SelectorTypes/ChoiceList/MultipleSelect/MultipleSelect.jsx
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx

https://jira.jahia.org/browse/BACKLOG-14318

BACKLOG-14318 : add new selector for selenium when select is readOnly

---

src/javascript/SelectorTypes/ChoiceList/MultipleSelect/actions/selectAll.action.js
src/javascript/SelectorTypes/Picker/actions/index.js
src/javascript/SelectorTypes/Picker/actions/openInTab.action.js
src/javascript/SelectorTypes/Picker/actions/replace.action.js
src/javascript/SelectorTypes/actions/unsetField.action.js

https://jira.jahia.org/browse/QA-13094

QA-13094 : add context.key manually for choicelist actions

---

src/javascript/ContentEditor.constants.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/ChildrenSection/ChildrenSection.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx

https://jira.jahia.org/browse/BACKLOG-14321

BACKLOG-14321 integrate automatically orderable

---

src/javascript/ContentEditor.context.js
src/javascript/Create/Create.adapter.js
src/javascript/Edit/Edit.adapter.js
src/javascript/Edit/EditForm.gql-queries.js
src/javascript/EditPanel/EditPanelContent/EditPanelContent.jsx
src/javascript/EditPanel/EditPanelContent/EditPanelContent.spec.jsx
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorForm.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/StaticDefinitionsRegistry.java
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_category.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_contentFolder.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_folder.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_group.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_groupsFolder.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_user.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_virtualsite.json
src/main/resources/META-INF/jahia-content-editor-forms/forms/nt_base.json
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/definitions.cnd
src/test/resources/META-INF/jahia-content-editor-forms/forms/nt_base.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/jmix_hasPreview.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/jnt_content.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/jnt_folder.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/jnt_text.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/nt_base.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/nt_base.priority.json
src/test/resources/META-INF/jahia-content-editor-forms/overrides/forms/nt_base.same-priority.json

https://jira.jahia.org/browse/BACKLOG-12887

BACKLOG-12887 : Hide preview for some nodeTypes.

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.spec.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.gql-queries.jsx

https://jira.jahia.org/browse/BACKLOG-14392

BACKLOG-14392 : add direct parent in breadcrumb

---

src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14294

BACKLOG-14294 : fix typo in WIP FR message

---

src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_usersFolder.json

https://jira.jahia.org/browse/BACKLOG-14412

BACKLOG-14412 : hide preview for users folder content type

---

src/javascript/SelectorTypes/SystemName/SystemName.jsx
src/javascript/SelectorTypes/SystemName/SystemName.onChange.js
src/javascript/SelectorTypes/SystemName/SystemName.onChange.spec.js
src/javascript/SelectorTypes/SystemName/SystemName.spec.js
src/javascript/SelectorTypes/SystemName/SystemName.utils.jsx
src/javascript/SelectorTypes/SystemName/SystemName.utils.spec.js
src/javascript/SelectorTypes/Text/Text.jsx
src/javascript/SelectorTypes/Text/Text.test.jsx

https://jira.jahia.org/browse/BACKLOG-14441

BACKLOG-14441 : limit the system name size

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14440

BACKLOG-14440 : change system name helper

---

src/javascript/EditPanel/EditPanelDialogConfirmation/EditPanelDialogConfirmation.jsx

https://jira.jahia.org/browse/BACKLOG-14411

BACKLOG-14411 add max width to dialog confirmation

---

src/javascript/SelectorTypes/SystemName/SystemName.jsx
src/javascript/SelectorTypes/SystemName/SystemName.onChange.js
src/javascript/SelectorTypes/SystemName/SystemName.onChange.spec.js
src/javascript/SelectorTypes/SystemName/SystemName.utils.jsx
src/javascript/SelectorTypes/SystemName/SystemName.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-14442

BACKLOG-14442 : handle special characters in system name and lowercase

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-14424

BACKLOG-14424 : consider propertyList of json override

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-14499

BACKLOG-14499 extend createNewContent action to support globallink

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-14545

BACKLOG-14545 : update content editor signature for 3.1.x

---

src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js

https://jira.jahia.org/browse/BACKLOG-14425

BACKLOG-14425 : synchronize on change calls for dependent properties

---

src/javascript/EditPanel/header/UpperSection.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-14585

BACKLOG-14585 : remove context from back button buttons actions

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-14592

BACKLOG-14592 update DisplayActions context

---

src/javascript/Create/CreateForm/create.request.js
src/javascript/Edit/save/save.request.js

https://jira.jahia.org/browse/BACKLOG-14599

BACKLOG-14599 : add onCreate / onEdit hooks

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormRuntimeException.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/lock/StaticEditorLockService.java

https://jira.jahia.org/browse/BACKLOG-14408

BACKLOG-14408 : fix sonar issues

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-14609

BACKLOG-14609 : clean up + add context node path

---

src/javascript/Edit/publish/publish.action.jsx
src/javascript/Edit/publish/publish.action.spec.js
src/javascript/Edit/startWorkflow/startWorkflow.action.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.spec.js
src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-14592

BACKLOG-14592 update publish & startWorkflow actions

---

src/javascript/EditPanel/EditPanel.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/EditPanel/header/LowerSection.jsx
src/javascript/EditPanel/header/LowerSection.scss

https://jira.jahia.org/browse/MOON-150

MOON-150: Styling to make EditPanel header better reflect design

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java

https://jira.jahia.org/browse/BACKLOG-14616

BACKLOG-14616 : fix section overriding

---

src/javascript/Edit/publish/publish.action.jsx
src/javascript/Edit/publish/publish.action.spec.js

https://jira.jahia.org/browse/BACKLOG-14629

BACKLOG-14629 update publish.action.jsx

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.action.spec.jsx

https://jira.jahia.org/browse/BACKLOG-14634

BACKLOG-14634 : use the right uuid when creating the translation request

---

src/javascript/Edit/startWorkflow/startWorkflow.action.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.spec.js

https://jira.jahia.org/browse/BACKLOG-14630

BACKLOG-14630 disable publish request btn when form is dirty

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.actions.jsx
src/javascript/SelectorTypes/ChoiceList/ChoiceList.actions.js
src/javascript/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/BACKLOG-14654

BACKLOG-14654 : adapt field menu to contextual menu changes.

---

src/javascript/Edit/save/save.gql-mutation.js
src/javascript/Edit/save/save.request.js

https://jira.jahia.org/browse/BACKLOG-14651

BACKLOG-14651 : fix preview path in case name change

---

package.json
yarn.lock

https://jira.jahia.org/browse/QA-13154

QA-13154 update dependencies

---

src/javascript/SelectorTypes/SystemName/SystemName.jsx
src/javascript/SelectorTypes/SystemName/SystemName.utils.jsx
src/javascript/SelectorTypes/SystemName/SystemName.utils.spec.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-14498

BACKLOG-14498 : fix title and system name comparison to hide copy button

---

src/javascript/SelectorTypes/Picker/ContentPicker/index.js
src/javascript/SelectorTypes/Picker/MediaPicker/index.js
src/javascript/SelectorTypes/Picker/PickerContainer.jsx
src/main/resources/javascript/locales/en.json

https://jira.jahia.org/browse/QA-13158

QA-13158 handle case when reference not found

---

src/main/java/org/jahia/modules/contenteditor/api/lock/StaticEditorLockService.java

https://jira.jahia.org/browse/SELENIUM-1284

SELENIUM-1284: fixed error when clearing locks after disconnection

---

src/javascript/SelectorTypes/Picker/ContentPicker/index.js
src/javascript/SelectorTypes/Picker/ContentPicker/index.spec.js
src/javascript/SelectorTypes/Picker/MediaPicker/index.js
src/javascript/SelectorTypes/Picker/MediaPicker/index.spec.js
src/javascript/SelectorTypes/Picker/PickerContainer.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/QA-13158

QA-13158 handle case when reference not found & locales

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-13341

QA-13341 : use UI locale to display choicelist values

---

src/javascript/Edit/engineTabs/openEngineTabs.action.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/GoToOption.action.jsx
src/javascript/EditPanel/EditPanel.actions.js
src/javascript/EditPanel/header/LowerSection.jsx
src/javascript/EditPanel/tabbar/tabbar.action.jsx
src/javascript/EditPanel/tabbar/tabbar.action.spec.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/MainPanel.jsx
src/javascript/actions/editRestricted.action.jsx

https://jira.jahia.org/browse/BACKLOG-14845

BACKLOG-14845 : remove context from displayactions and from some actions

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.action.spec.jsx
src/javascript/Edit/EditContent.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.action.jsx
src/javascript/Edit/copyLanguage/copyLanguage.action.spec.jsx
src/javascript/Edit/engineTabs/openEngineTabs.action.jsx
src/javascript/Edit/publish/publish.action.jsx
src/javascript/Edit/publish/publish.action.spec.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.jsx
src/javascript/Edit/startWorkflow/startWorkflow.action.spec.js
src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/GoToOption.action.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.jsx
src/javascript/EditPanel/WorkInProgress/OpenWorkInProgressModal.action.spec.js
src/javascript/EditPanel/header/ActionsButtons.jsx
src/javascript/EditPanel/tabbar/tabbar.action.jsx
src/javascript/actions/goBack.action.jsx

https://jira.jahia.org/browse/BACKLOG-14847

Backlog 14847 remove context from actions

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-14926

BACKLOG-14926 : fix proptypes for CreateNewContent

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-14850

BACKLOG-14850 : Restore using content locale to display list values.

---

src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.gql-queries.jsx

https://jira.jahia.org/browse/BACKLOG-14946

BACKLOG-14946 : fix blank page on rename

---

src/javascript/DesignSystem/DatePicker/DatePicker.jsx

https://jira.jahia.org/browse/BACKLOG-14952

BACKLOG-14952 fix next/previous month tab navigation

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx

https://jira.jahia.org/browse/BACKLOG-15015

BACKLOG-15015 : add missing props due to action framework refactoring

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.container.jsx
src/javascript/SelectorTypes/SelectorTypes.js
src/javascript/SelectorTypes/SelectorTypes.spec.js

https://jira.jahia.org/browse/QA-13375

QA-13375 handle fallback selector type in case of unknown

---

src/javascript/Edit/publish/publish.action.jsx

https://jira.jahia.org/browse/BACKLOG-15025

BACKLOG-15025 fix publish action

---

src/javascript/SelectorTypes/Picker/ContentPicker/index.js

https://jira.jahia.org/browse/QA-13301

QA-13301 handle undefined of data jcr

---

src/javascript/SelectorTypes/Picker/PickerDialog/MainPanel.jsx
src/javascript/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/BACKLOG-15043

BACKLOG-15043 : restore selenium attribute on upload button

---

src/javascript/Edit/EditForm.gql-queries.js
src/javascript/Edit/save/save.gql-mutation.js
src/javascript/EditPanel/EditPanel.utils.js
src/javascript/EditPanel/EditPanel.utils.spec.js
src/javascript/Validation/validation.js
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-13450

QA-13450 : allow to have same name propety in dynamic choicelists

---

src/javascript/EditPanel/EditPanel.utils.js

https://jira.jahia.org/browse/QA-13450

QA-13450 : get list of activated fieldset properly.

---

src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js

https://jira.jahia.org/browse/BACKLOG-15098

BACKLOG-15098 : fix multiple dependent properties check

---

package.json
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.spec.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-15111
* The material UI Select component for the ChoiceList SingleSelect has been replaced with the Moonstone Dropdown
* Bump moonstone version to 0.17.4

BACKLOG-15111: Replaces ChoiceList SingleSelect selector with Moonstone Dropdown

---

src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.spec.jsx

https://jira.jahia.org/browse/BACKLOG-15113

BACKLOG-15113 : add image support in dropdown (Choicelist)

---

src/javascript/Validation/SaveModal/SaveErrorModal.jsx

https://jira.jahia.org/browse/BACKLOG-15192

BACKLOG-15192 fix SaveErrorModal

---

src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.jsx
src/javascript/DesignSystem/SiteSwitcher/SiteSwitcher.spec.js

https://jira.jahia.org/browse/BACKLOG-15190

BACKLOG-15190 : add Selenium selector attributes

---

src/main/import/roles.xml

https://jira.jahia.org/browse/QA-13505

QA-13505: Add node permission to owner role

---

pom.xml

https://jira.jahia.org/browse/TECH-256

TECH-256 : use release verstion of graphql

---

.npmrc
package.json
src/javascript/SelectorTypes/Picker/PickerDialog/LeftPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/LeftPanel.scss
yarn.lock

https://jira.jahia.org/browse/BACKLOG-15157

BACKLOG-15157: Fixed tree color and size, removed npm repo

---

src/javascript/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/Thumbnail/Thumbnail.jsx

https://jira.jahia.org/browse/BACKLOG-15224

BACKLOG-15224 : unregister upload image refetch

---

src/javascript/Edit/save/save.gql-mutation.js

https://jira.jahia.org/browse/BACKLOG-15150

BACKLOG-15150 rename node first

---

package.json
webpack.config.js
yarn.lock

https://jira.jahia.org/browse/QA-13541

QA-13541 : fix webpack configuration for svg loading

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Section/FieldSet/Field/Field.container.spec.jsx
src/javascript/SelectorTypes/Picker/Picker.configs.js
src/javascript/SelectorTypes/SelectorTypes.js
src/javascript/SelectorTypes/SelectorTypes.spec.js

https://jira.jahia.org/browse/BACKLOG-15353

Backlog 15353 fix 3 dots displaying

---

src/javascript/SelectorTypes/RichText/RichText.utils.js
src/javascript/SelectorTypes/RichText/RichText.utils.spec.js

https://jira.jahia.org/browse/BACKLOG-15358

BACKLOG-15358 : get correctly the picker from the registry for richtext

---

src/javascript/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/Thumbnail/Thumbnail.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-15224

BACKLOG-15224 : use remove registry function

---

src/javascript/SelectorTypes/Picker/ContentPicker/index.js

https://jira.jahia.org/browse/QA-13517

QA-13517 : use blank uuid instead of to avoid GQL error

---

src/javascript/SelectorTypes/Picker/MediaPicker/index.js
src/javascript/SelectorTypes/Picker/Picker.configs.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/QA-13326

QA-13326 : Improve picker labels

---

src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss

https://jira.jahia.org/browse/BACKLOG-15379

BACKLOG-15379: Fix for Copy Language Modal

---

src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.jsx
src/javascript/EditPanel/CopyLanguageDialog/CopyLanguageDialog.scss

https://jira.jahia.org/browse/BACKLOG-15379

BACKLOG-15379: Fix for language dropdown getting cut off in Copy Language modal

---

src/javascript/SelectorTypes/SelectorTypes.onChange.js

https://jira.jahia.org/browse/BACKLOG-15409

BACKLOG-15409 : use updated sections after being modified

---

pom.xml

Revert version to 3.1.0-SNAPSHOT

Reverted version to prepare repo for release

---

package.json

https://jira.jahia.org/browse/QA-13616
Use double quotes to make builds work on Windows

QA-13616: Make project buildable on Windows

---

src/javascript/SelectorTypes/Picker/actions/index.js

https://jira.jahia.org/browse/QA-13585

QA-13585: ContentPickerMenu - Change the way isShowIcons prop is passed

---

pom.xml

BACKLOG-15501: bump yarn to 1.22.10

---

package.json
pom.xml

Backlog 15501

---

.eslintrc.json

https://jira.jahia.org/browse/BACKLOG-15504
Fixing 'unique' json issue found during release

BACKLOG-15504: Fixing 'unique' json issue found during release

---

.eslintrc.json
pom.xml

https://jira.jahia.org/browse/Backlog-15504
Fix unique issue on eslinting

Backlog-15504: Fix unique issue on eslinting

---

pom.xml
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorFormMutations.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorSubscriptions.java
yarn.lock

https://jira.jahia.org/browse/TECH-210
* Update parent artifact version
* Update graphql dependency versions
* Refactor GraphQLContext references

TECH-210: Update GraphQL dependencies

---

pom.xml
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorFormMutations.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorSubscriptions.java
yarn.lock

https://jira.jahia.org/browse/TECH-210
Use ContextUtil to fetch http request for GQL context

TECH-210: Use ContextUtil to fetch http request for GQL context

---

src/javascript/Edit/Edit.jsx
src/javascript/Edit/save/save.request.js
src/javascript/EditPanel/EditPanel.refetches.js
src/javascript/pagecomposer.redux-actions.js

https://jira.jahia.org/browse/QA-13804
Notify page composer on systemname change

Qa 13804 pc action

---

src/javascript/PublicationInfo/PublicationInfo.jsx

https://jira.jahia.org/browse/QA-13902
Fixes undefined exception

QA-13902 Fix undefined error

---

src/javascript/Edit/publish/publish.gql-mutation.js
src/javascript/Edit/publish/publish.request.js
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorFormMutations.java

…nd the associated technical sub nodes

Rework publish now

---

src/javascript/Create/Create.actions.js

https://jira.jahia.org/browse/BACKLOG-16471
https://github.com/Jahia/jcontent/pull/472

BACKLOG-16471: disable new page until jcontent is enabled

---

pom.xml

https://jira.jahia.org/browse/QA-13999 
Use latest SNAPSHOT of the module-test-framework

QA-13999: Use latest SNAPSHOT of the module-test-framework

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-14015
Fix choicelist of numbers.
Make such definition
``` 
- col1Width (long, choicelist) = '33' < '20', '33', '50', '66', '80'
```
work

QA-14015 : fix choicelist of numbers

---

src/javascript/Api/ContentEditor.api.jsx

prevent creation of unneeded element without its required properties

Fixed react warning

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-14157

QA-14157: check definition match before getting values

---

src/javascript/SelectorTypes/Picker/Picker.configs.js

https://jira.jahia.org/browse/QA-14179
Allow to select jnt:navMenuText in page tree

QA-14179 Allow to select jnt:navMenuText in page tree

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-14058

QA-14058 : fix mixin order

---

src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/EditPanel/header/ContentBreadcrumb/ContentPath/ContentPath.container.spec.jsx
src/javascript/FormDefinitions/FormDefinitions.js
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java

https://jira.jahia.org/browse/QA-14183
Avoid flickering of old values by not calling dispatch if in redux mode 

QA-14183: Avoid flickering of old values by not calling dispatch if in redux mode 

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-16863
Add null value check

BACKLOG-16863 Add null value check

---

webpack.shared.js

https://jira.jahia.org/browse/BACKLOG-16940
Share formik as singleton so that other modules can access formik hooks when needed ( https://github.com/Jahia/copy-to-other-languages/pull/10 )

BACKLOG-16940: Share formik as singleton

---

src/javascript/ContentEditor.context.js
src/javascript/ContentEditor.helper.jsx
src/javascript/ContentEditor.helper.spec.js
src/javascript/ContentEditorSection/ContentEditorSection.context.jsx
src/javascript/SelectorTypes/ChoiceList/ChoiceList.onChange.js
src/javascript/SelectorTypes/SelectorTypes.onChange.js

https://jira.jahia.org/browse/BACKLOG-16941

BACKLOG-16941: Fixed sections and fieldset update

---

src/javascript/Api/ContentEditor.api.jsx
src/javascript/ContentEditor.constants.js
src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/Edit/save/save.action.jsx
src/javascript/Edit/save/save.action.spec.jsx
src/javascript/actions/goBack.action.jsx
src/javascript/utils/getKeydownListener.js

https://jira.jahia.org/browse/BACKLOG-16827
Keydown functionality for ctrl+s and esc

BACKLOG-16827 Add keydown functionality

---

src/javascript/Edit/Edit.jsx
src/javascript/EditPanel/EditPanel.refetches.js
src/javascript/EditPanel/EditPanelContent/Preview/Preview.fetcher.js

https://jira.jahia.org/browse/BACKLOG-17038

BACKLOG-17038: Invalidate refetcher at correct place

---

src/javascript/Api/ContentEditor.api.jsx

https://jira.jahia.org/browse/BACKLOG-17060
Restore focus to prevent breaking advanced options

BACKLOG-17060 Restore focus

---

src/javascript/Api/ContentEditor.api.jsx

https://jira.jahia.org/browse/BACKLOG-16827
Focus window without affecting other functionality

BACKLOG-16827 Focus window without affecting other functionality

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Edit/save/save.action.jsx

https://jira.jahia.org/browse/BACKLOG-16826
Fix issue on windows

BACKLOG-16826 Fix issue on windows

---

src/javascript/Create/CreateForm/create.action.js
src/javascript/Edit/save/save.action.jsx

https://jira.jahia.org/browse/BACKLOG-16826
Add command key

BACKLOG-16826 Add command key

---

src/javascript/SelectorTypes/SystemName/SystemName.jsx
src/javascript/SelectorTypes/SystemName/SystemName.onChange.js
src/javascript/SelectorTypes/SystemName/SystemName.utils.jsx
src/javascript/SelectorTypes/SystemName/SystemName.utils.spec.js

https://jira.jahia.org/browse/QA-14081

QA-14081: Fixed systemname transform

---

src/javascript/Create/CreateNewContentAction/createNewContent.utils.js

https://jira.jahia.org/browse/BACKLOG-16830
Fixed invalid result type

BACKLOG-16830: Fixed page creation

---

src/javascript/Create/CreateForm/createForm.gql-mutation.js
src/javascript/Edit/save/save.gql-mutation.js

https://jira.jahia.org/browse/BACKLOG-17090

BACKLOG-17090 : Missing cache fields

---

src/javascript/Api/ContentEditorModal.jsx
src/javascript/Api/ContentTypeSelectorModal.jsx
src/javascript/Api/useCreate.js
src/javascript/Api/useEdit.js
src/javascript/ContentEditor.register.jsx

https://jira.jahia.org/browse/BACKLOG-17094

BACKLOG-17094: Add custom callbacks for gwt

---

src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx

https://jira.jahia.org/browse/BACKLOG-17093

BACKLOG-17093: focus on first field

---

src/javascript/SelectorTypes/Picker/ContentPicker/ContentPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/PickerDialog/Views/content.gql-queries.js

https://jira.jahia.org/browse/TECH-320

TECH-320: Add missing cache fields

---

src/javascript/SelectorTypes/Picker/PickerDialog/Views/useDialogPickerContent.jsx

https://jira.jahia.org/browse/BACKLOG-17083
Fix fetchMore updateQuery merging functions, use data coming from the newly fetched data instead of the previous ones

BACKLOG-17083: Fix fetchMore updateQuery merging functions

---

.stylelintrc.json
src/javascript/Api/ContentEditorModal.jsx
src/javascript/Create/Create.jsx
src/javascript/Create/CreateForm/create.action.js
src/javascript/Create/CreateForm/create.action.spec.js
src/javascript/EditPanel/EditPanel.scss
src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx
src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.scss
src/javascript/actions/ActionsButtons.jsx
src/javascript/utils/getButtonRenderer.jsx
src/main/resources/javascript/locales/en.json

https://jira.jahia.org/browse/BACKLOG-16832

BACKLOG-16832: Save and create new, styling

---

src/main/java/org/jahia/modules/contenteditor/api/lock/StaticEditorLockService.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorFormMutations.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorSubscriptions.java

https://jira.jahia.org/browse/BACKLOG-16486

BACKLOG-16486: Added logging on locks

---

src/javascript/SelectorTypes/Picker/PickerContainer.jsx

https://jira.jahia.org/browse/BACKLOG-17110
Do not wrap reference card in picker

BACKLOG-17110 Do not wrap reference card in picker

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/Field/Field.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-17093

BACKLOG-17093: Focus only first field, handle richtext

---

package.json
src/javascript/Api/ContentEditorModal.jsx
src/javascript/ContentEditor.redux.jsx
src/javascript/ContentEditor.register.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/Field/Field.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/redux/registerReducer.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-17107
Track section state with redux

BACKLOG-17107 Track section state with redux

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/Section/Section.jsx

https://jira.jahia.org/browse/BACKLOG-17118
Don't display section if no fieldset

BACKLOG-17118 Don't display section if no fieldset

---

src/javascript/Api/ContentEditorModal.jsx
src/javascript/ContentEditor.redux.jsx
src/javascript/Create/CreateForm/create.request.js
src/javascript/Create/CreateForm/create.request.spec.js
src/javascript/Edit/save/save.request.js
src/javascript/Edit/save/save.request.spec.js

https://jira.jahia.org/browse/BACKLOG-16833

BACKLOG-16833: Create and edit

---

src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/actions/goBack.action.jsx
src/javascript/utils/getButtonRenderer.jsx

https://jira.jahia.org/browse/BACKLOG-16837

BACKLOG-16837: Fixed cancel button

---

src/javascript/EditPanel/EditPanelDialogConfirmation/SaveButton.jsx

https://jira.jahia.org/browse/BACKLOG-16837

BACKLOG-16837: don't close modal if form is unsaved

---

src/javascript/EditPanel/EditPanel.scss
src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/EditPanel/EditPanelContent/EditPanelContent.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.scss
src/javascript/EditPanel/Validation.jsx
src/javascript/EditPanel/Validation.scss
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-17133

BACKLOG-17133: Add validation banner

---

src/javascript/Api/ContentEditorModal.jsx
src/javascript/EditPanel/EditPanel.scss
src/javascript/EditPanel/EditPanelCompact.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-16836
Add "advanced mode". Translation is being collected.

BACKLOG-16836 Add "advanced mode"

---

src/javascript/EditPanel/Validation.scss

https://jira.jahia.org/browse/BACKLOG-17152

BACKLOG-17152: Fixed styling

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-17150

BACKLOG-17150: Add translations

---

src/javascript/Create/Create.jsx

https://jira.jahia.org/browse/BACKLOG-17158
Remove onblur validation in create mode

BACKLOG-17158 Remove onblur validation in create mode

---

src/javascript/ContentEditor.register.jsx

https://jira.jahia.org/browse/BACKLOG-17145
Refresh content in repository explored after creation

BACKLOG-17145 Refresh content in repository explored after creation

---

src/javascript/Api/ContentEditorModal.jsx

https://jira.jahia.org/browse/BACKLOG-17163
Remove edit option if in full screen

BACKLOG-17163 Remove edit option if in full screen

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-17127

BACKLOG-17127 - Update version to 4.0.0

---

src/javascript/EditPanel/EditPanelLanguageSwitcher/EditPanelLanguageSwitcher.jsx

https://jira.jahia.org/browse/BACKLOG-17166

BACKLOG-17166: Add icon

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-17164

BACKLOG-17164: Fixed notification hook

---

src/javascript/ContentEditor.constants.js
src/javascript/Edit/Edit.adapter.js
src/javascript/Edit/Edit.adapter.spec.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/ChildrenSection/AutomaticOrdering/AutomaticOrdering.spec.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/ChildrenSection/AutomaticOrdering/AutomaticOrdering.utils.js
src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/ChildrenSection/ChildrenSection.jsx
src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/OrderingSection/OrderingSection.jsx
src/javascript/FormDefinitions/FormData.adapter.js
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-17129
Instead of creating an ordering section on the fly I return one from server to make things a little more predictable/manageable

BACKLOG-17129 Make sure there is always a list ordering section if one is needed

---

src/javascript/Api/ContentEditorApi.jsx
src/javascript/Api/useCreate.js
src/javascript/Api/useEdit.js
src/javascript/ContentEditor.redux.jsx
src/javascript/ContentEditor.register.jsx
src/javascript/ContentEditorHistory/ContentEditorHistory.jsx
src/javascript/utils/useSwitchLanguage.js

https://jira.jahia.org/browse/BACKLOG-17109

BACKLOG-17109: Handle language override, restore previous language

---

src/javascript/EditPanel/EditPanelCompact.jsx

https://jira.jahia.org/browse/BACKLOG-16836

BACKLOG-16836 Do not show advanced mode in create modal

---

src/javascript/EditPanel/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/EditPanel/EditPanelCompact.jsx
src/javascript/EditPanel/header/HeaderLowerSection.jsx
src/javascript/utils/getButtonRenderer.jsx

https://jira.jahia.org/browse/BACKLOG-17159

BACKLOG-17159: fixed buttons rendering

---

src/javascript/Api/OnCloseConfirmationDialog.jsx

https://jira.jahia.org/browse/BACKLOG-17168

BACKLOG-17168: trigger validation when displaying confirmation dialog

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/OrderingSection/OrderingSection.jsx

https://jira.jahia.org/browse/BACKLOG-17129
Restore previous behaviour

BACKLOG-17129 Keep previous behaviour for ordering section

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-16844
https://github.com/Jahia/content-editor/pull/1039

BACKLOG-16844: fixed ckeditor

---

src/javascript/Api/ContentEditorApi.scss
src/javascript/ContentEditor.context.js
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.jsx
src/javascript/Create/CreateNewContentAction/CreateNewContentDialog.scss
src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/Field/Field.scss
src/javascript/EditPanel/EditPanelContent/FormBuilder/Sections/ChildrenSection/AutomaticOrdering/AutomaticOrdering.jsx
src/javascript/SelectorTypes/Picker/MediaPicker/index.js

https://jira.jahia.org/browse/BACKLOG-17115

BACKLOG-17115: More ui fixes

---

src/javascript/EditPanel/EditPanel.utils.js
src/javascript/EditPanel/EditPanelHeader/UnsavedChip.jsx
src/javascript/EditPanel/Validation.jsx
src/javascript/SelectorTypes/SystemName/SystemName.onChange.js
src/javascript/SelectorTypes/SystemName/SystemName.onChange.spec.js
src/javascript/Validation/validation.utils.js
src/javascript/utils/useSwitchLanguage.js

https://jira.jahia.org/browse/BACKLOG-17203
Use one language to sync system name

BACKLOG-17203 Use one language to sync system name

---

src/javascript/SelectorTypes/Category/category.adapter.js

https://jira.jahia.org/browse/QA-14323

QA-14323: Fix lint issue

---

src/javascript/SelectorTypes/Category/Category.jsx
src/javascript/SelectorTypes/Category/Category.spec.jsx

https://jira.jahia.org/browse/QA-14314

QA-14314: handle single-value category

---

package.json
src/javascript/ContentEditor/EditPanel/EditPanelHeader/EditPanelHeader.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx
yarn.lock

Rollback changes in Field.jsx, use moonstone 2.4.0 and avoid using DisplayAction for GoBack component as in EditPanelCompact
https://jira.jahia.org/browse/BACKLOG-17228

BACKLOG-17228: Rollback changes in Field.jsx, use moonstone 2.4.0

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-17254

BACKLOG-17254: Fixed label override

---

src/javascript/SelectorTypes/SystemName/SystemName.onChange.js

https://jira.jahia.org/browse/BACKLOG-17285
related to #1158

BACKLOG-17285: Fixed system name sync

---

src/javascript/ContentEditor/EditPanel/EditPanelHeader/ContentPath/ContentPath.jsx
src/javascript/ContentEditor/EditPanel/EditPanelHeader/PublishMenu.jsx
src/javascript/ContentEditor/EditPanel/WindowListeners.jsx
src/javascript/ContentEditorApi/OnCloseConfirmationDialog.jsx
src/javascript/actions/contenteditor/goBackAction.jsx
src/javascript/actions/contenteditor/publish/publishAction.jsx
src/javascript/actions/contenteditor/save/saveAction.jsx
src/javascript/actions/contenteditor/startWorkflow/startWorkflowAction.jsx
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/openEngineTabsAction.jsx
src/javascript/utils/fields.utils.js

https://jira.jahia.org/browse/BACKLOG-17287

BACKLOG-17287: fixed dirty flag

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/Section/Section.jsx

https://jira.jahia.org/browse/BACKLOG-17300
Use name if section displayName is empty

BACKLOG-17300 Use name if section displayName is empty

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldValue.java
tests/cypress/e2e/addMixinChoicelistInitializers.cy.ts

https://jira.jahia.org/browse/BACKLOG-17236

BACKLOG-17236: Ensure we return date formatted in the specified TZ, without the TZ information

---

src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-17314

BACKLOG-17314: Corectly update value when prop is changed

---

src/javascript/SelectorTypes/Picker/Picker.jsx

https://jira.jahia.org/browse/BACKLOG-17317

BACKLOG-17317: fixed cancel button

---

src/javascript/ContentEditor/EditPanel/HeaderBadges/UnsavedChip.jsx
src/javascript/utils/useSwitchLanguage.js

https://jira.jahia.org/browse/BACKLOG-17305

BACKLOG-17305 : Fixed unsaved chip, fixed language switching

---

src/javascript/validation/onServerError.js

https://jira.jahia.org/browse/BACKLOG-17346

BACKLOG-17346: Fixed server validation error

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-17139

BACKLOG-17139: Update signature

---

src/javascript/SelectorTypes/Picker/Picker.jsx
src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/Picker2.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/MainPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.spec.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/List/List.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/Thumbnail/Thumbnail.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/Views/useDialogPickerContent.jsx
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/Picker.configs.js
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/configs/configPropType.js

https://jira.jahia.org/browse/BACKLOG-17223

BACKLOG-17223: Override picker and accordions config

---

src/javascript/SelectorTypes/Picker/Picker2.constants.js
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.scss
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.scss
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/index.js
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/actions/registerPickerActions.js
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/reactTable/columns/columns.js
src/javascript/SelectorTypes/Picker/reactTable/columns/index.js

https://jira.jahia.org/browse/BACKLOG-17225
Incorporate table from jcontent

BACKLOG-17225 Incorporate table from jcontent

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.spec.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.spec.js

https://jira.jahia.org/browse/BACKLOG-17286

BACKLOG-17286: Allow to display or not the site switcher in the tree navigation

---

package.json
src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/configs/ContentPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/MediaPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.js
src/javascript/SelectorTypes/Picker/reactTable/plugins/index.js
src/javascript/SelectorTypes/Picker/reactTable/plugins/useRowSelection.jsx
src/javascript/SelectorTypes/Picker/reactTable/plugins/useSort.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-17373
Fix selection

BACKLOG-17373 Fix selection

---

src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.spec.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.spec.js

BACKLOG-17373 Fix unit tests

---

package.json
src/javascript/SelectorTypes/Picker/Picker2.constants.js
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.gql-queries.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/index.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/index.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/usePreloadedData.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.scss
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/accordionItems/renderer.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-1739
We should be back to where we were, selection reset during navigation issue was also addressed.

BACKLOG-17395 Use layout container and table directly, fix navigation issues

---

src/javascript/ContentEditor/create.gql-queries.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/SelectorTypes/Picker/Picker2.jsx
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormField.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormProperty.java

https://jira.jahia.org/browse/BACKLOG-17223

BACKLOG-17223: Allow json override

---

src/javascript/ContentEditor.proptypes.js
src/javascript/ContentEditor/ContentEditor.jsx
src/javascript/ContentEditor/EditPanel/EditPanel.jsx
src/javascript/ContentEditor/EditPanel/EditPanel.scss
src/javascript/ContentEditor/EditPanel/EditPanelCompact.jsx
src/javascript/ContentEditor/EditPanel/EditPanelFullscreen.jsx
src/javascript/ContentEditorApi/ContentEditorApi.jsx
src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/ContentEditorApi/ContentTypeSelectorModal.jsx
src/javascript/ContentEditorApi/useCreate.js
src/javascript/ContentEditorApi/useEdit.js
src/javascript/__mocks__/@jahia/jahia-ui-root.js
src/javascript/actions/jcontent/renameContent/RenameLayout.jsx
src/javascript/actions/jcontent/renameContent/RenameLayout.scss
src/javascript/actions/jcontent/renameContent/renameContentAction.jsx
src/javascript/actions/jcontent/renameContent/useRenameFormDefinition.jsx
src/javascript/actions/registerEditActions.js
src/javascript/contexts/ContentEditor/ContentEditor.context.js
src/javascript/contexts/ContentEditor/useFormDefinitions.js
src/javascript/contexts/ContentEditorApi/ContentEditorApi.context.jsx
src/javascript/contexts/ContentEditorApi/index.js
src/javascript/contexts/index.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/Section/Section.jsx
src/javascript/register.jsx
src/javascript/shared/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-17190
- allows to specify layout for ui
- can customize useFormDefinition hook 
- use context for providing api

BACKLOG-17190: Rename dialog

---

package.json
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.scss
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.scss
src/javascript/SelectorTypes/Picker/accordionItems/renderer.jsx
yarn.lock

https://jira.jahia.org/browse/[BACKLOG-17395](https://jira.jahia.org/browse/BACKLOG-17395)

BACKLOG-17395: Add picker layout

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/__mocks__/@jahia/jcontent.js

https://jira.jahia.org/browse/BACKLOG-17576

BACKLOG-17576: Fixed refetch

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.gql-queries.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/reactTable/plugins/useRowSelection.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-17502
Add translation
Add isSelectable to query for flexibility, this should make it easier to determine what is selectable and what's not without hardcoding types.

BACKLOG-17502 Add translation, add isSelectable to query for flexibility

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/resources/META-INF/jahia-content-editor-forms/forms/nt_base.json

https://jira.jahia.org/browse/QA-14365

QA-14365 : fix display of ordering section with permissions

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.spec.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/index.js
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js

https://jira.jahia.org/browse/BACKLOG-17577

BACKLOG-17577: Fixed picker in Richtext

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.scss
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx
src/javascript/SelectorTypes/RichText/RichText.scss
webpack.shared.js

https://jira.jahia.org/browse/BACKLOG-19846

BACKLOG-19846 : Share material-ui/core for modal manager, fixed ckeditor modal

---

src/javascript/ContentEditor/EditPanel/EditPanel.scss
src/javascript/ContentEditor/EditPanel/EditPanelCompact.jsx
src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/actions/contenteditor/goBackAction.jsx
src/javascript/actions/jcontent/renameContent/RenameLayout.jsx
src/javascript/actions/jcontent/renameContent/RenameLayout.scss
src/javascript/actions/jcontent/renameContent/renameContentAction.jsx
src/javascript/actions/jcontent/renameContent/useRenameFormDefinition.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx

https://jira.jahia.org/browse/BACKLOG-19848

BACKLOG-19848: fixes for rename

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/accordionItems/renderer.jsx
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-19841
Make selection persistent
We are still waiting for feedback from Felix for some behaviours but selection persistence has been decided.

BACKLOG-19841 Persist selection when navigating

---

src/javascript/ContentEditorRoute/ContentEditorRoute.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/contexts/ContentEditor/ContentEditor.context.js

https://jira.jahia.org/browse/BACKLOG-19852

BACKLOG-19852: reselect node when reopening the picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

https://jira.jahia.org/browse/BACKLOG-17225

BACKLOG-17225 : Remove debounce on simple selection

---

src/javascript/SelectorTypes/Picker/Picker2.redux.js

Reset pagination everytime path changes

Reset pagination everytime path changes

---

src/javascript/ContentEditorRoute/ContentEditorRoute.jsx

https://jira.jahia.org/browse/BACKLOG-19855

BACKLOG-19855: Enable confirmation dialog

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

Don't show view type selector if pages cannot be selected

Don't show view type selector if pages cannot be selected

---

src/javascript/SelectorTypes/Picker/Picker2.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19871
Simple site picker with just name column in the table

BACKLOG-19871 Add config and accordion for site picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

https://jira.jahia.org/browse/BACKLOG-19872
Make sure selection column is not removed if column config is specified

BACKLOG-19872 Make picker work with multiple selection

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-19902

BACKLOG-19902 - Provide translations

---

src/javascript/SelectorTypes/Picker/Picker2.constants.js
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19896
Return undefined if sites not found in path

BACKLOG-19896 Return undefined if sites not found in path

---

src/javascript/SelectorTypes/Picker/Picker2.constants.js
src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.scss
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx

https://jira.jahia.org/browse/BACKLOG-19907

BACKLOG-19907: Use dedicated search mode

---

src/javascript/ContentEditor/EditPanel/EditPanelCompact.jsx
src/javascript/editorTabs/EditPanelContent/Preview/Preview.utils.js
tests/cypress/e2e/previewContent.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/pageComposer.ts

https://jira.jahia.org/browse/QA-14201
Add a cypress test to validate scenario

QA-14201: Fix page preview if edited node path != currentPage.path in Page Composer

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

https://jira.jahia.org/browse/BACKLOG-19910

BACKLOG-19910: Remove highlight in multiple

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx

https://jira.jahia.org/browse/BACKLOG-19911

BACKLOG-19911: Adds open in jcontent action in picker

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx

https://jira.jahia.org/browse/BACKLOG-19904

BACKLOG-19904: reset search upon picker opening

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-19917

BACKLOG-19917: Dispatch actions from picker dialog

---

src/javascript/SelectorTypes/Picker/Picker2.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/accordionItems/queryHandlers.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/main/resources/javascript/locales/en.json

https://jira.jahia.org/browse/BACKLOG-19867

BACKLOG-19867: User picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/MediaPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/javascript/SelectorTypes/Picker/configs/configPropType.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-19928

BACKLOG-19928: Cleaned and fixed labels

---

src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19930
Do not display site switcher for site picker

BACKLOG-19930 Do not display site switcher for site picker

---

src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx

https://jira.jahia.org/browse/BACKLOG-19927

BACKLOG-19927: Add default order per accordion config

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
tests/cypress/e2e/addMixinChoicelistInitializers.cy.ts
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/e2e/pickers/pickerMultiple.cy.ts
tests/cypress/e2e/pickers/pickerTypes.cy.ts
tests/cypress/e2e/pickers/search.cy.ts
tests/cypress/fixtures/pickers/contentTypes.ts
tests/cypress/page-object/pageComposer.ts
tests/cypress/page-object/picker.ts
tests/cypress/page-object/pickerField.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/BACKLOG-19932

BACKLOG-19932: added tests on tree picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx

https://jira.jahia.org/browse/BACKLOG-19929

BACKLOG-19929: Fixed site switching

---

src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/accordionItems/queryHandlers.gql-queries.js
src/javascript/SelectorTypes/Picker/accordionItems/queryHandlers.jsx
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/pickers/usergroup.cy.ts

https://jira.jahia.org/browse/BACKLOG-19869

BACKLOG-19869: Add group of users picker configuration

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
tests/cypress/e2e/pickers/user.cy.ts

https://jira.jahia.org/browse/BACKLOG-19943

BACKLOG-19943: Extend search query with mode fragments

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/e2e/pickers/pickerMultiple.cy.ts
tests/cypress/e2e/pickers/pickerTree.cy.ts
tests/cypress/e2e/pickers/search.cy.ts
tests/cypress/page-object/jcontent.ts
tests/cypress/page-object/picker.ts

https://jira.jahia.org/browse/BACKLOG-19929

BACKLOG-19929: Fixed browsing with selection

---

src/javascript/SelectorTypes/Picker/accordionItems/QueryHandlers/queryHandlers.jsx
tests/cypress/e2e/pickers/usergroup.cy.ts

BACKLOG-19945: list both global and sites user/groups

---

src/javascript/SelectorTypes/Picker/accordionItems/QueryHandlers/queryHandlers.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19947

BACKLOG-19947: display first/last name

---

src/javascript/SelectorTypes/Picker/Picker2.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/accordionItems/accordionItems.jsx
src/javascript/SelectorTypes/Picker/reactTable/plugins/useExpanded.jsx
src/javascript/SelectorTypes/Picker/reactTable/plugins/useRowMultipleSelection.jsx
tests/cypress.config.ts
tests/cypress/e2e/pickers/search.cy.ts
tests/cypress/page-object/picker.ts

https://jira.jahia.org/browse/BACKLOG-17385
* Expand tab for the given selection
* Expand structure view tree to the given selection
* Fix bug in missing multiple selection checkbox for structure view
* Fix cypress tests

BACKLOG-17385: Expand selection in structured view

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx

https://jira.jahia.org/browse/BACKLOG-19950

BACKLOG-19950: Reset pagination when reopening picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.gql-queries.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/SelectionTable.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/SelectionTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/selectionColumns.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
tests/cypress.config.ts

https://jira.jahia.org/browse/BACKLOG-19870

BACKLOG-19870: Allow to render custom columns in selection table

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
tests/cypress/e2e/pickers/editoriallink.cy.ts
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/e2e/pickers/pickerMultiple.cy.ts
tests/cypress/page-object/picker.ts
tests/cypress/page-object/pickerTable.ts

https://jira.jahia.org/browse/BACKLOG-19952

BACKLOG-19952: Refactor picker table cypress component

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.gql-queries.jsx

https://jira.jahia.org/browse/BACKLOG-19954

BACKLOG-19954: Add name

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

https://jira.jahia.org/browse/BACKLOG-19944

BACKLOG-19944: Scroll to top whn changing page

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-19935

BACKLOG-19935: Typo in labels

---

tests/cypress/e2e/pickers/constraint.cy.ts
tests/cypress/e2e/pickers/richtext.cy.ts
tests/cypress/e2e/pickers/site.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/picker.ts
tests/cypress/page-object/richTextField.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/BACKLOG-19948

BACKLOG-19948: Added more tests

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/configs/renderer.jsx
src/javascript/registerReducer.js

https://jira.jahia.org/browse/BACKLOG-19908

BACKLOG-19908: Add ce language in redux

---

src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/ContentEditorRoute/ContentEditorRoute.jsx
src/javascript/registerReducer.js

https://jira.jahia.org/browse/BACKLOG-19908

BACKLOG-19908: Update redux state when using modal

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerSiteSwitcher.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/configs/ContentPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/MediaPickerConfig.js

https://jira.jahia.org/browse/BACKLOG-19877

BACKLOG-19877: use override in selectionHandler

---

src/javascript/SelectorTypes/Picker/configs/NoIconPickerCaption.js
src/javascript/SelectorTypes/Picker/configs/sitePicker.js
src/javascript/SelectorTypes/Picker/configs/userPicker.js
src/javascript/SelectorTypes/Picker/configs/usergroupPicker.js

Depends on https://github.com/Jahia/jcontent/pull/590

BACKLOG-19959: Do not display for user/site/usergroup picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js

https://jira.jahia.org/browse/BACKLOG-19847

BACKLOG-19847: filter images

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/actions/registerPickerActions.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/reactTable/columns/CellVisibleActions.jsx
src/javascript/SelectorTypes/Picker/reactTable/columns/Cells.scss
src/javascript/SelectorTypes/Picker/reactTable/columns/columns.js
tests/cypress/e2e/addMixinChoicelistInitializers.cy.ts

https://jira.jahia.org/browse/BACKLOG-20006

BACKLOG-20006: Adds contextual and 3dots menu

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
tests/cypress/e2e/pickers/search.cy.ts

https://jira.jahia.org/browse/BACKLOG-20009

BACKLOG-20009: Allows fileGrid in search

---

src/javascript/SelectorTypes/Picker/configs/Picker2.configs.js

https://jira.jahia.org/browse/BACKLOG-19859

BACKLOG-19859: Add actions in media picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/SelectionTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/PickerSelection/selectionColumns.jsx
src/javascript/SelectorTypes/Picker/configs/categoryPicker.js
src/javascript/SelectorTypes/Picker/configs/contentFolderPicker.js
src/javascript/SelectorTypes/Picker/configs/folderPicker.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/configs/pagePicker.js
src/javascript/SelectorTypes/Picker/configs/sitePicker.js
src/javascript/SelectorTypes/Picker/configs/userPicker.js
src/javascript/SelectorTypes/Picker/configs/usergroupPicker.js
src/javascript/SelectorTypes/Picker/reactTable/columns/FileSizeCell.jsx
src/javascript/SelectorTypes/Picker/reactTable/columns/RelPathCell.jsx
src/javascript/SelectorTypes/Picker/reactTable/columns/columns.js
src/javascript/SelectorTypes/Picker/reactTable/columns/rowPropType.jsx

https://jira.jahia.org/browse/BACKLOG-19983

BACKLOG-19983: Split columns configuration

---

src/javascript/SelectorTypes/Picker/configs/categoryPicker.js
src/javascript/SelectorTypes/Picker/configs/folderPicker.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/configs/pagePicker.js
src/javascript/SelectorTypes/Picker/configs/sitePicker.js
src/javascript/SelectorTypes/Picker/configs/userPicker.js
src/javascript/SelectorTypes/Picker/configs/usergroupPicker.js

https://jira.jahia.org/browse/BACKLOG-19983

BACKLOG-19983: Add missing column configuration

---

src/javascript/SelectorTypes/Picker/actions/openInTabAction.gql-queries.js
src/javascript/SelectorTypes/Picker/actions/openInTabAction.js
src/javascript/SelectorTypes/Picker/actions/openInTabAction.spec.js
src/javascript/SelectorTypes/Picker/reactTable/columns/CellVisibleActions.jsx

https://jira.jahia.org/browse/BACKLOG-17390

BACKLOG-17390: Modify openInTabAction to be working either from picker field or form actions menu

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-17351

BACKLOG-17351: Allow to unselect card by clicking on them

---

src/javascript/ContentEditor/ContentEditor.jsx
src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/ContentEditorRoute/ContentEditorRoute.jsx
src/javascript/actions/contenteditor/create/createAction.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx

https://jira.jahia.org/browse/QA-14461

QA-14461: Recall field listener after 'create new'

---

src/javascript/SelectorTypes/Picker/configs/sitePicker.js

https://jira.jahia.org/browse/BACKLOG-19959

BACKLOG-19959: do not display icon in site picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx

Try to fix failing test by keeping same columns as in current mode

Fixed columns in search

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx
tests/cypress/e2e/pickers/editoriallink.cy.ts

https://jira.jahia.org/browse/BACKLOG-19979

BACKLOG-19979: Show navMenuText items in editorial link picker

---

src/javascript/validation/validate.js
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/systemNameTest.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/pageComposer.ts

https://jira.jahia.org/browse/QA-14040
Validate system name before saving
Note that I'm using the same chars in regex as used in replace functionality we already have.

QA-14040 System name validation

---

src/javascript/Create/CreateForm/createForm.gql-queries.js
src/javascript/Create/CreateNewContentAction/CreateNewContent.gql-queries.js
src/javascript/Edit/EditForm.gql-queries.js
src/javascript/SelectorTypes/Category/category.gql-queries.js
src/javascript/SelectorTypes/Picker/ContentPicker/ContentPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/MediaPicker/MediaPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/Picker.utils.js
src/javascript/SelectorTypes/Picker/PickerDialog/Search/FolderName.gql-queries.js
src/javascript/SelectorTypes/Picker/PickerDialog/Views/content.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-20028

BACKLOG-20028: Apollo cache fixes

---

src/javascript/validation/validate.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/systemNameTest.cy.ts

https://jira.jahia.org/browse/QA-14040
Update regex as discussed with QA

QA-14040 Update functionality

---

src/javascript/actions/registerEditActions.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-20029

BACKLOG-20029: Remove rename

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-20027

BACKLOG-20027: Use empty drop zone

---

src/javascript/SelectorTypes/SystemName/SystemName.utils.spec.js

https://jira.jahia.org/browse/QA-14040

QA-14040 : Fixed test

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx

https://jira.jahia.org/browse/BACKLOG-20017

BACKLOG-20017: Skip errors on invalid openpaths

---

src/javascript/SelectorTypes/Picker/Picker2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/EditorialLinkContentTypeSelector.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/EditorialContentTypeSelector.js
src/javascript/init.js
tests/docker-compose.yml

https://jira.jahia.org/browse/BACKLOG-19987
- Do not modify registered configs
- Pass picker config down to table/grid and table header
- Removed invalid code in SelectionHandler

BACKLOG-19987: Fixed config override

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/editorialLinkPicker.js

https://jira.jahia.org/browse/BACKLOG-17390

BACKLOG-17390: add contextual menu in editorialLinkPicker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx

enable select only if there is nodes

---

src/javascript/register.jsx

https://jira.jahia.org/browse/QA-14040
Same as https://github.com/Jahia/jahia-private/commit/384f8fc39419e7792f5fa735c480a09c8c6bc618

QA-14040: encode uri before redirect

---

src/javascript/SelectorTypes/RichText/RichText.utils.js

https://jira.jahia.org/browse/BACKLOG-20060

BACKLOG-20060: Fixed picker config

---

README.md
src/javascript/SelectorTypes/Picker/configs/pagePicker.js

https://jira.jahia.org/browse/BACKLOG-19980
Added publication status to the page picker

BACKLOG-19980 - Added publication status to the page picker

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx
src/javascript/SelectorTypes/Picker/configs/mediaPicker/PickerFilesQueryHandler.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.spec.js
src/javascript/SelectorTypes/Picker/configs/queryHandlers.jsx

https://jira.jahia.org/browse/BACKLOG-19856

BACKLOG-19856: Allow to define a fieldFilter to filter children/descendants to be fetched.

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx

https://jira.jahia.org/browse/BACKLOG-20063

BACKLOG-20063: set site if rootpath is on another site

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx
src/javascript/SelectorTypes/Picker/configs/mediaPicker/PickerFilesQueryHandler.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/configs/queryHandlers.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/pickers/pdf.cy.ts
tests/cypress/page-object/contentEditor.ts

https://jira.jahia.org/browse/BACKLOG-19856

BACKLOG-19856: fix search fieldFilter if a selectableFilter is declared

---

src/javascript/SelectorTypes/Picker/configs/mediaPicker/MediaPicker.gql-queries.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.spec.js

https://jira.jahia.org/browse/BACKLOG-20084 
Get mimetype from children, update test

BACKLOG-20084 Get mimetype from children, update test

---

src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js

…
https://jira.jahia.org/browse/BACKLOG-19856

BACKLOG-19856: Add tableDisplayFilter to the PickerContentsFolderQueryHandler

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx
tests/cypress/e2e/pickers/editoriallink.cy.ts

https://jira.jahia.org/browse/BACKLOG-20011

BACKLOG-20011: changed recursion filter

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-19944

BACKLOG-19944: reset scroll in files grid

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
src/javascript/SelectorTypes/Picker/configs/categoryPicker.js
src/javascript/SelectorTypes/Picker/configs/sitePicker.js
src/javascript/SelectorTypes/Picker/configs/userPicker.js
src/javascript/SelectorTypes/Picker/configs/usergroupPicker.js

https://jira.jahia.org/browse/BACKLOG-20063

BACKLOG-20063: Fixed nav without changing site

---

src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js

https://jira.jahia.org/browse/BACKLOG-20102

BACKLOG-20102: Add picker config for droppableContent

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20031

BACKLOG-20031: bump moonstone version

---

src/javascript/SelectorTypes/Picker/Picker2.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/RightPanel.jsx
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js

https://jira.jahia.org/browse/QA-14367
Also removed unused pickerKey from redux state

QA-14367: select uploaded file, fixed upload in grid

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog2.jsx

https://jira.jahia.org/browse/BACKLOG-20031

BACKLOG-20031: Remove transform style after transition

---

src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx

https://jira.jahia.org/browse/BACKLOG-20101
Follow up to PR https://github.com/Jahia/content-editor/pull/1346 to also apply the same filter in structure view.

BACKLOG-20101: Add page-type filter for content tab (structured view)

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js

https://jira.jahia.org/browse/BACKLOG-20121

BACKLOG-20121: Use configurable auto-expand

---

.github/workflows/nightly.yml

https://jira.jahia.org/browse/BACKLOG-20046

BACKLOG-20046 - Fix nightly startup

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20143
Moonstone update

BACKLOG-20143 Moonstone update

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-20135

BACKLOG-20135: Define minimum required version of jcontent

---

src/javascript/init.js

https://jira.jahia.org/browse/BACKLOG-20171

BACKLOG-20171: Add download action

---

README.md

https://jira.jahia.org/browse/BACKLOG-20201
Github actions didn't trigger on-merge workflow (build/publish) on last commit possibly due to some issues https://www.githubstatus.com/incidents/5kjgx4x2frkw . Forcing a merge to re-trigger.

BACKLOG-20201: Force build

---

src/javascript/ContentEditor.constants.js
src/javascript/ContentEditor/adaptEditFormData.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/ChildrenSection/ChildrenSection.jsx

https://jira.jahia.org/browse/BACKLOG-20117

BACKLOG-20117: enable ordering on pages

---

src/javascript/ContentEditor/adaptEditFormData.js
src/javascript/ContentEditor/adaptEditFormData.spec.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/SelectorTypes/Picker/actions/previewInTabAction.gql-queries.js
src/javascript/SelectorTypes/Picker/actions/previewInTabAction.js
src/javascript/SelectorTypes/Picker/actions/registerPickerActions.js
src/javascript/SelectorTypes/Picker/reactTable/columns/Cells.scss
src/javascript/SelectorTypes/Picker/reactTable/columns/LocationCell.jsx
src/javascript/SelectorTypes/Picker/reactTable/columns/columns.js
src/javascript/contexts/ContentEditor/ContentEditor.context.js
src/javascript/editorTabs/AdvancedOptions/AdvancedOptions.jsx
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.scss
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.jsx
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.scss
src/javascript/editorTabs/AdvancedOptions/Usages/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-17186
Warning: Preview action not implemented only open in new tab as of now.

BACKLOG-17186: Add usages screen

---

src/javascript/actions/registerCreateActions.js

https://jira.jahia.org/browse/BACKLOG-20113

BACKLOG-20113: Use config to enable pagecomposer

---

src/javascript/SelectorTypes/Picker/actions/previewInTabAction.js
src/javascript/SelectorTypes/Picker/actions/registerPickerActions.js
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.jsx
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.scss

https://jira.jahia.org/browse/BACKLOG-17186
- Fix preview action, 
- change icon for open in new tab, 
- fix spacing in usages screen

BACKLOG-17186: Fix preview action, change icon for open in new tab

---

src/javascript/SelectorTypes/Picker/actions/previewInTabAction.js

https://jira.jahia.org/browse/BACKLOG-20231

BACKLOG-20231: Do not render previewInTabAction if data is undefined

---

pom.xml
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-20250
With JContent < 2.9 there is non Drag and Drop context exposed

BACKLOG-20250: Ensure we use JContent 2.9 for DND purposes

---

src/javascript/actions/registerEditActions.js

https://jira.jahia.org/browse/BACKLOG-20114

BACKLOG-20114: remove edit,editInPage from selectedContentActions

---

src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx
tests/cypress/e2e/pickers/constraint.cy.ts
tests/cypress/e2e/pickers/customPicker.cy.ts
tests/cypress/e2e/pickers/displayActions.cy.ts

https://jira.jahia.org/browse/QA-14194
Update tests

QA-14194 Update tests

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.scss
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.spec.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/ChildrenSection/ListSizeLimitFieldSet/ListSizeLimitFieldSet.spec.jsx

https://jira.jahia.org/browse/BACKLOG-20236
https://www.figma.com/file/stKLXxFYWhsLx8WZgRtZBN/DESIGN-1153%3A-Improving-the-CE-structure-understanding?node-id=1790%3A1684&t=8ByjqM15zHkL44B5-0
Also merged Static/Dynamic fieldSet

BACKLOG-20236: Adjust form styles

---

src/javascript/ContentEditor/EditPanel/HeaderBadges/ReadOnlyBadge.jsx

https://jira.jahia.org/browse/BACKLOG-20105
Check every field in section

BACKLOG-20105 Check every field in section

---

src/javascript/SelectorTypes/Boolean/Boolean.scss

https://jira.jahia.org/browse/BACKLOG-20212

BACKLOG-20212: Fix hover when disabled and checked

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/ChildrenSection/ChildrenSection.jsx

https://jira.jahia.org/browse/BACKLOG-20370
Check for undefined

BACKLOG-20370 Check for undefined

---

src/javascript/actions/registerCreateActions.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACLOG-20115

BACLOG-20115: Moved create actions into menu

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/Row.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.scss
tests/cypress/e2e/pickers/pdf.cy.ts
tests/cypress/e2e/pickers/picker.cy.ts
tests/cypress/page-object/picker.ts

https://jira.jahia.org/browse/BACKLOG-11062

BACKLOG-11062: Use dnd from jcontent

---

src/javascript/SelectorTypes/MultipleLeftRightSelector/MultipleLeftRightSlector.scss
src/javascript/SelectorTypes/MultipleLeftRightSelector/ValueList/ValueList.jsx
src/javascript/SelectorTypes/MultipleLeftRightSelector/ValueList/ValueList.scss

https://jira.jahia.org/browse/BACKLOG-20215
Update css

BACKLOG-20215 Update css

---

src/javascript/ContentEditor/edit.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-20310

BACKLOG-20310 filter references type

---

src/javascript/SelectorTypes/Picker/actions/previewInTabAction.gql-queries.js
src/javascript/SelectorTypes/Picker/actions/previewInTabAction.js

https://jira.jahia.org/browse/BACKLOG-20308

BACKLOG-20308: Fixed preview action

---

src/javascript/ContentEditor/adaptEditFormData.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/SelectorTypes/Picker/reactTable/columns/Cells.scss
src/javascript/SelectorTypes/Picker/reactTable/columns/LocationCell.jsx

https://jira.jahia.org/browse/BACKLOG-20372

BACKLOG-20372: Add locale badges

---

src/javascript/ContentEditor/edit.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-20312

BACKLOG-20312: Add information in reference nodes

---

src/javascript/DesignSystem/OrderableValue/OrderableValue.jsx

https://jira.jahia.org/browse/BACKLOG-20374
https://jira.jahia.org/browse/BACKLOG-20378

BACKLOG-20374: disable reordering for read-only

---

src/javascript/SelectorTypes/Picker/actions/previewInTabAction.js

https://jira.jahia.org/browse/BACKLOG-20311

BACKLOG-20311: check undefined

---

src/javascript/ContentEditor/edit.gql-queries.js

https://jira.jahia.org/browse/BACKLOG-20398

BACKLOG-20398: Exclude workflowTask only

---

src/javascript/editorTabs/AdvancedOptions/Usages/Usages.jsx

https://jira.jahia.org/browse/BACKLOG-20400

BACKLOG-20400: Avoid infinite render loop

---

src/javascript/DesignSystem/OrderableValue/OrderableValue.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/MultipleField.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/MultipleField.spec.jsx

https://jira.jahia.org/browse/BACKLOG-20375

BACKLOG-20375: Add a drop zone after all values

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/editorialLinkPicker.js
src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js
src/javascript/SelectorTypes/Picker/configs/pagePicker.js

https://jira.jahia.org/browse/BACKLOG-11062

BACKLOG-11062: Disable pickers in tree

---

src/javascript/actions/registerCreateActions.js
src/javascript/actions/registerEditActions.js

https://jira.jahia.org/browse/BACKLOG-20303

BACKLOG-20303: Enable/disable actions based on pageComposer settings

---

.github/workflows/get-dependencies-updates.yml
.github/workflows/on-code-change.yml

https://jira.jahia.org/browse/TECH-1024

TECH-1024 - Update workflows to use new dependencies checks

---

src/javascript/SelectorTypes/Picker/reactTable/columns/LocationCell.jsx

https://jira.jahia.org/browse/BACKLOG-20410

BACKLOG-20410: Limit number of displayed badges

---

src/javascript/SelectorTypes/Picker/Picker.jsx
tests/cypress/e2e/pickers/pickerMultiple.cy.ts

https://jira.jahia.org/browse/BACKLOG-20375

BACKLOG-20375: Fixed reordering in pickers

---

src/javascript/actions/contenteditor/startWorkflow/startWorkflowAction.jsx

https://jira.jahia.org/browse/BACKLOG-19878

BACKLOG-19878: Removed broken test

---

src/javascript/SelectorTypes/Picker/Picker.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx

https://jira.jahia.org/browse/QA-14623

QA-14623: multiple selection with file upload

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx
src/javascript/SelectorTypes/Picker/configs/editorialPicker/editorialPicker.js
tests/cypress/e2e/pickers/categories.cy.ts
tests/cypress/e2e/pickers/displayActions.cy.ts
tests/cypress/e2e/pickers/editoriallink.cy.ts
tests/cypress/support/e2e.js

https://jira.jahia.org/browse/BACKLOG-20281

BACKLOG-20281: lower auto-expand

---

package.json
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/AdvancedOptionsNavigation.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20373

BACKLOG-20373: Use light badge

---

src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.jsx

https://jira.jahia.org/browse/BACKLOG-20401

BACKLOG-20401: Fixed fetch of displayName

---

src/javascript/SelectorTypes/Picker/Picker.redux.js
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/Search.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/SelectionHandler.jsx

https://jira.jahia.org/browse/BACKLOG-20381

BACKLOG-20381: removed contextsite, always reset to current site

---

src/javascript/ContentEditorApi/ContentEditorModal.jsx

https://jira.jahia.org/browse/BACKLOG-20426

BACKLOG-20426: Fixed test

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.action.spec.jsx

https://jira.jahia.org/browse/BACKLOG-20430
see  #1444 

BACKLOG-20430: Fix contextMenu rendering for menus with createNewContent.action.jsx

---

src/javascript/utils/fields.utils.js
tests/cypress/e2e/language.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/fields/field.ts
tests/cypress/page-object/fields/index.js
tests/cypress/page-object/fields/pickerField.ts
tests/cypress/page-object/fields/richTextField.ts
tests/cypress/page-object/fields/smallTextField.ts
tests/cypress/page-object/jcontent.ts

https://jira.jahia.org/browse/QA-14628
- Fix missing parameter bug when saving content with multi-language
- Added cypress test for creating content with multi-language
- Refactored some of the field cypress page objects

QA-14628: Fix issue when saving content with multi language

---

package.json
src/javascript/localesHash.js
src/javascript/register.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20421
Adds hash of each locale file in jahia.localeFiles , to be used by app-shell i18n backend

BACKLOG-20421: Adds locales hash calculation

---

src/javascript/SelectorTypes/Picker/actions/openInTabAction.js

https://jira.jahia.org/browse/QA-14502

QA-14502: Fixed action

---

package.json
src/javascript/DesignSystem/ReferenceCard/ReferenceCard.jsx
src/javascript/SelectorTypes/Picker/Picker.jsx
src/javascript/SelectorTypes/Picker/configs/DefaultPickerConfig.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
yarn.lock

https://jira.jahia.org/browse/[QA-14502

QA-14502: Update design for reference card

---

src/javascript/SelectorTypes/Picker/configs/mediaPicker/mediaPicker.js

https://jira.jahia.org/browse/QA-14502
Keep default message for image picker

QA-14502: Fixed label

---

src/javascript/SelectorTypes/Picker/configs/DefaultPickerConfig.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.js

https://jira.jahia.org/browse/QA-14502

QA-14502: Fixed cached error handling

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-16838

BACKLOG-16838 : set minimum graphql version

---

src/javascript/Create/CreateNewContentAction/createNewContent.action.jsx
src/javascript/Create/CreateNewContentAction/createNewContent.action.spec.jsx

…
https://jira.jahia.org/browse/BACKLOG-20430

BACKLOG-20430: Fix contextMenu rendering for menus with createNewContent.action.jsx (#1454)

---

src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-20493

BACKLOG-20493: Fixed previous selection

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentTable/Row.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-20497
Update usage of useFileDrop / useDrop api. 
Fixed dnd in files Grid 
Port update of  dnd design ( https://jira.jahia.org/browse/BACKLOG-20414 )

BACKLOG-20497: Update dnd api

---

src/javascript/contexts/ContentEditorApi/index.js

from https://github.com/Jahia/content-editor/pull/1495

BACKLOG-20435: fix wrong export of the contentEditorApi.context

---

package.json
src/javascript/ContentEditor/create.gql-queries.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/SelectorTypes/Boolean/registerBoolean.js
src/javascript/SelectorTypes/Category/registerCategory.js
src/javascript/SelectorTypes/ChoiceList/SingleSelect/SingleSelect.jsx
src/javascript/SelectorTypes/ChoiceList/registerChoiceList.jsx
src/javascript/SelectorTypes/Color/registerColor.js
src/javascript/SelectorTypes/DateTimePicker/registerDateTimePicker.js
src/javascript/SelectorTypes/MultipleLeftRightSelector/registerMultipleLeftRightSelector.jsx
src/javascript/SelectorTypes/Picker/registerPicker.js
src/javascript/SelectorTypes/RichText/registerRichText.js
src/javascript/SelectorTypes/Tag/registerTag.js
src/javascript/SelectorTypes/Text/registerText.js
src/javascript/SelectorTypes/TextAreaField/registerTextAreaField.js
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldValueConstraint.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetFieldTest.java
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20462

Backlog 20462 add labels and icons

---

src/javascript/ContentEditor/EditPanel/HeaderBadges/WipInfoChip.spec.js
src/javascript/ContentEditor/create.gql-queries.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/ContentEditor/useEditFormDefinition.js
src/javascript/ContentEditor/useEditFormDefinition.spec.js
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.spec.jsx

https://jira.jahia.org/browse/QA-14516

QA-14516: Use wip default settings

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx

https://jira.jahia.org/browse/SUP-228

SUP-228 : handle correctly autoExpandLevels when it is aquals to 0

---

src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/ContentEditorRoute/ContentEditorRoute.jsx
src/javascript/SelectorTypes/ChoiceList/registerChoiceListOnChange.js
src/javascript/SelectorTypes/registerSelectorTypesOnChange.js
src/javascript/contexts/ContentEditor/ApolloCacheFlushOnGWTSave.jsx
src/javascript/contexts/ContentEditor/ContentEditor.context.js
src/javascript/contexts/ContentEditorSection/ContentEditorSection.context.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FormBuilder.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FormBuilder.spec.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Validation.jsx
src/javascript/registerReducer.js
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/resources/META-INF/jahia-content-editor-forms/forms/nt_base.json
tests/.env.example
tests/env.debug.sh

https://jira.jahia.org/browse/BACKLOG-20536

BACKLOG-20536: removed redux state, fixed sections context

---

src/javascript/EditPanel/EditPanelContent/FormBuilder/FieldSet/Field/Field.jsx

https://jira.jahia.org/browse/BACKLOG-17144
#1361 

BACKLOG-17144: Backport fix from https://github.com/Jahia/content-editor/pull/1361

---

.github/maven.settings.xml
.github/workflows/get-dependencies-updates.yml
.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml
.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1081
Update deprecated steps

TECH-1081 Update deprecated steps

---

.github/workflows/on-merge.yml

https://jira.jahia.org/browse/TECH-1081

TECH-1081 - Fix typo

---

src/javascript/SelectorTypes/Picker/PickerDialog/RightPanel/ContentLayout/ContentLayout.container.jsx

https://jira.jahia.org/browse/BACKLOG-20563
https://github.com/Jahia/content-editor/pull/1520 backport

BACKLOG-20563: Add max limit to auto-expand levels config value (backport)

---

src/javascript/actions/contenteditor/openWorkInProgress/openWorkInProgressAction.jsx

https://jira.jahia.org/browse/QA-14601
Check if node is locked before displaying wip

QA-14601 Check if node is locked before displaying wip

---

src/javascript/DesignSystem/DropdownTreeSelect/DropdownTreeSelect.jsx

https://jira.jahia.org/browse/QA-14667
Increase zIndex to prevent overlay issues

QA-14667 Increase zIndex to prevent overlay issues

---

src/javascript/utils/fields.utils.js

https://jira.jahia.org/browse/QA-14708

QA-14708: Avoid property removal when not translated

---

src/javascript/SelectorTypes/RichText/RichText.jsx

https://jira.jahia.org/browse/BACKLOG-20258
Enable spellcheck for CKeditor

BACKLOG-20258 Enable spellcheck for CKeditor

---

src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/actions/jcontent/createContent/createContent.utils.js
src/javascript/actions/jcontent/createContent/createContent.utils.spec.js
src/main/resources/META-INF/configurations/org.jahia.modules.contentEditor.cfg
src/main/resources/configs/contentEditor.jsp

https://jira.jahia.org/browse/BACKLOG-20119
Allow to specify the number of buttons to render up to 10.

BACKLOG-20119: Ensure we refresh page upon new node creation. 

---

src/javascript/SelectorTypes/Category/Category.jsx

https://jira.jahia.org/browse/QA-14662

QA-14662: Removed placeholder

---

src/javascript/ContentEditor.constants.js
src/javascript/ContentEditor/edit.gql-queries.js
src/javascript/ContentEditor/useEditFormDefinition.js

https://jira.jahia.org/browse/QA-14637

QA-14637: Add jmix:navMenuItem in childrenFilterTypes and use supertypes.name for filtering

---

src/javascript/SelectorTypes/MultipleLeftRightSelector/registerMultipleLeftRightSelector.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-20643

BACKLOG-20643 : update icon name in MultipleLeftRightSelector

---

src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorFormMutations.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java

https://jira.jahia.org/browse/QA-14696

QA-14696: fixed locale parsing

---

src/javascript/actions/contenteditor/create/createAction.js

https://jira.jahia.org/browse/BACKLOG-17202

BACKLOG-17202: resetI18nContext before formik resetForm

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx

https://jira.jahia.org/browse/BACKLOG-20420

BACKLOG-20420: keep parameters, use 2 effects

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/test/java/org/jahia/modules/DummyBundle.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java

https://jira.jahia.org/browse/BACKLOG-20565

BACKLOG-20565: Allow to use override per site

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
src/test/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/QA-14606
Tests module available in ticket

QA-14606: Add supertypes for added mixins on a node. Add test case, and extra verification in existing ones

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSet.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldTarget.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSetTest.java

https://jira.jahia.org/browse/BACKLOG-20698

BACKLOG-20698: Fixed comparison inconsistency

---

tests/cypress/e2e/pickers/pdf.cy.ts
tests/cypress/page-object/picker.ts

Fix cypress test as part of port of #1553 to CE 4.2.x
- Need to also add fix to cypress test found here https://github.com/Jahia/content-editor/commit/54d760dd3d4906cf0e767c1ba1ab3b7424b84e38#diff-99a72d6145f7122fbd1d04029f40749e5236a0a4d33ab20c9e5a5a0e2fd418e0R179 as part of moonstone change and also include fixes from this PR https://github.com/Jahia/content-editor/pull/1549

Fix cypress tests - fix search input selector

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx

https://jira.jahia.org/browse/BACKLOG-20731

BACKLOG-20731: refactor content editor url/state handling

---

src/javascript/SelectorTypes/RichText/RichText.jsx
src/javascript/SelectorTypes/RichText/RichText.scss

https://jira.jahia.org/browse/QA-14713

QA-14713: Fix fullscreen hiding dialogs in background.

---

tests/cypress/e2e/pickers/customPicker.cy.ts
tests/cypress/fixtures/pickers/contentTypes.ts
tests/cypress/fixtures/pickers/createCustomContent.graphql

https://jira.jahia.org/browse/TECH-1070

TECH-1070: change tests to use custom pickers

---

src/javascript/SelectorTypes/Tag/Tag.jsx

https://jira.jahia.org/browse/QA-14757

QA-14757: send empty array when removing tags

---

src/javascript/SelectorTypes/Picker/configs/editorialPicker/PickerPagesQueryHandler.jsx
src/javascript/SelectorTypes/Picker/configs/pagePicker.js
tests/cypress/e2e/pickers/pages.cy.ts
tests/cypress/fixtures/pickers/createContent.graphql
tests/cypress/fixtures/pickers/deleteContent.graphql

https://jira.jahia.org/browse/QA-14764

QA-14764: Add jmix:navMenuItem as openableTypes, and add cypress for page picker

---

src/javascript/editorTabs/AdvancedOptions/Usages/Usages.gql-queries.js
src/javascript/editorTabs/AdvancedOptions/Usages/Usages.jsx

https://jira.jahia.org/browse/QA-14748
Fix issue when loading usages screen by using pagination

QA-14748: Add pagination in usages

---

src/javascript/ContentEditorApi/ContentEditorModal.jsx
src/javascript/ContentEditorRoute/ContentEditorRoute.jsx

https://jira.jahia.org/browse/QA-14532

QA-14532: Autohide notification

---

src/javascript/SelectorTypes/RichText/RichText.utils.js

https://jira.jahia.org/browse/QA-14697

QA-14697: Fix invalid link file with a "plus" in filename.

---

src/javascript/SelectorTypes/RichText/RichText.scss

https://jira.jahia.org/browse/QA-14796

QA-14796: Fix CKEditor dropdowns not displayed in default screen mode.

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/BACKLOG-20858

Backlog 20858: Prepare release to 4 3 1

---

src/javascript/utils/getChildrenOrder.js

https://jira.jahia.org/browse/QA-14802

QA-14802 : fix issue when saving node with one child with reordering.

---

src/javascript/actions/jcontent/createContent/createContentAction.jsx

https://jira.jahia.org/browse/BACKLOG-20623

BACKLOG-20623: Disable create content action on lock

---

.github/workflows/schedule-sonar.yml

- Workflow can now be triggered manually
- A matrix job allows the check to be executed on all supported branches

TECH-1134: Added capability to run manually and across all supported branches

---

pom.xml
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.spec.jsx
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/BACKLOG-20616

BACKLOG-20616: Allow sanitized html in field/fieldset descriptions

---

package.json
src/javascript/editorTabs/EditPanelContent/Preview/Preview.utils.js
src/javascript/editorTabs/EditPanelContent/Preview/PreviewViewers/PreviewViewers.jsx
yarn.lock

https://jira.jahia.org/browse/QA-14483
Waiting on
https://github.com/Jahia/javascript-components/pull/233
Then will need to update data helper version

QA-14483: Use mimeType ig available to figure file type, icon and preview

---

tests/cypress/e2e/savePublishButtonsFlow.cy.ts
tests/cypress/fixtures/graphql/jcrPublicationStatus.graphql
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/jcontent.ts
tests/yarn.lock

https://jira.jahia.org/browse/TECH-1128

TECH-1128: Add save publish buttons flow test

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-20616

BACKLOG-20616 exclude guava

---

src/javascript/actions/jcontent/createContent/createContent.utils.js
src/javascript/actions/jcontent/createContent/createContentAction.jsx
src/javascript/actions/registerCreateActions.js

https://jira.jahia.org/browse/BACKLOG-20615

BACKLOG-20615: Add type icon

---

src/javascript/ContentTypeSelectorModal/ContentTypeSelectorModal.utils.js
src/javascript/actions/jcontent/createContent/createContent.utils.js

https://jira.jahia.org/browse/BACKLOG-20975

BACKLOG-20975: Replace default icon

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-14779

QA-14779: fixed error label

---

src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.jsx
src/javascript/SelectorTypes/Picker/PickerDialog/PickerDialog.scss

https://jira.jahia.org/browse/QA-14527

QA-14527: remove collapse button

---

src/javascript/EditPanel/header/UpperSection.jsx

https://jira.jahia.org/browse/BACKLOG-21107

BACKLOG-21107: fix publication icon

---

src/javascript/SelectorTypes/Picker/configs/editorialLinkPicker/PickerEditorialLinkQueryHandler.jsx
tests/cypress/e2e/pickers/editoriallink.cy.ts
tests/cypress/fixtures/pickers/createMainResources.graphql
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/QA-14844

QA-14844: allows to open mainresource

---

src/javascript/validation/validate.js
tests/cypress/e2e/textRegexInDefinition.cy.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

https://jira.jahia.org/browse/QA-14835

Qa 14835 fix consistency of regex validation

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-21042

BACKLOG-21042 - Update parent version

---

src/main/java/org/jahia/modules/contenteditor/api/forms/StaticDefinitionsRegistry.java

https://jira.jahia.org/browse/BACKLOG-20878

BACKLOG-20878: use warning logs

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx
src/javascript/SelectorTypes/Picker/actions/openInTabAction.gql-queries.js
src/javascript/SelectorTypes/Picker/actions/openInTabAction.js

https://jira.jahia.org/browse/BACKLOG-20851

BACKLOG-20851: Update url for 'open in new tab' in pickers

---

src/main/java/org/jahia/modules/contenteditor/api/forms/model/Field.java
src/main/java/org/jahia/modules/contenteditor/api/forms/model/FieldSet.java
tests/cypress/e2e/pickers/pdf.cy.ts
tests/cypress/e2e/textFieldInitializerTest.cy.ts
tests/cypress/page-object/contentEditor.ts

https://jira.jahia.org/browse/BACKLOG-20878
Some labels can be overridden in templates set , it was not taken into account in previous versions of CE.

BACKLOG-20878: Improved label resolutions in sites

---

src/main/java/org/jahia/modules/contenteditor/api/forms/model/Field.java
src/main/java/org/jahia/modules/contenteditor/api/forms/model/FieldSet.java

https://jira.jahia.org/browse/BACKLOG-21284

BACKLOG-21284: Default labels to node/item names

---

package.json
yarn.lock

https://jira.jahia.org/browse/QA-14618

QA-14618: fixed menu positioning

---

src/main/java/org/jahia/modules/contenteditor/api/forms/FormGenerator.java
src/main/java/org/jahia/modules/contenteditor/api/forms/StaticDefinitionsRegistry.java
src/main/java/org/jahia/modules/contenteditor/api/forms/model/FieldSet.java
src/test/java/org/jahia/modules/contenteditor/api/forms/EditorFormServiceImplTest.java

https://jira.jahia.org/browse/QA-14772

QA-14772: put fields in overridden fieldset

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.jsx

https://jira.jahia.org/browse/BACKLOG-21295

BACKLOG-21295: Hide dynamic mixin

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.spec.jsx

BACKLOG-21295: fix unit tests

---

tests/cypress/e2e/systemNameTest.cy.ts
tests/cypress/e2e/textFieldInitializerTest.cy.ts
tests/cypress/page-object/pageComposer.ts
tests/package.json
tests/yarn.lock

https://jira.jahia.org/browse/BACKLOG-21295

BACKLOG-21295: Location mixin

---

.graphqlconfig
schema.graphql
src/javascript/SelectorTypes/registerSelectorTypesOnChange.gql-queries.js
src/javascript/SelectorTypes/registerSelectorTypesOnChange.js

https://jira.jahia.org/browse/BACKLOG-21296
Issue was in dependent properties constraints being badly compared and missing some properties leading to a chain of refresh emptying the country

BACKLOG-21296: Ensure we do a deep copy of constraints and that we get same information in both queries

---

tests/cypress/e2e/contentEditorForm.cy.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd

https://jira.jahia.org/browse/QA-14772

QA-14772: Add test for overridden property in correct section

---

package.json
yarn.lock

https://jira.jahia.org/browse/QA-14618

QA-14618 - Update moonstone version

---

tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-21319

BACKLOG-21319 - Fix provisioning issues

---

tests/cypress/e2e/contentEditorForm.cy.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

https://jira.jahia.org/browse/QA-14793

QA-14793: Add new test to check custom label for buttons

---

src/javascript/editorTabs/EditPanelContent/FormBuilder/Sections/ChildrenSection/ManualOrdering/ManualOrdering.jsx

https://jira.jahia.org/browse/BACKLOG-21305
Open page composer create a new content list in an area issue/no issue

BACKLOG-21305: Fix issue when field has no children

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormServiceImpl.java
tests/cypress/e2e/contentEditorForm.cy.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

https://jira.jahia.org/browse/BACKLOG-21308

BACKLOG-21308: Fix constraints retrieval and add cypress test. Use same namespaces for all definitions.cnd

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/openEngineTabsAction.jsx

https://jira.jahia.org/browse/BACKLOG-21313
This fixes scenario 1 and 2 

BACKLOG-21313: Keep CE open after closing GWT dialog

---

tests/cypress/e2e/contentEditorForm.cy.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/META-INF/jahia-content-editor-forms/forms/cent_contentRetrievalCETest.json

https://jira.jahia.org/browse/BACKLOG-21287

BACKLOG-21287: Add new test case for override of hidden properties

---

src/javascript/ContentEditorApi/ContentEditorApi.jsx
src/javascript/editorTabs/AdvancedOptions/AdvancedOptionsNavigation/openEngineTabsAction.jsx

https://jira.jahia.org/browse/BACKLOG-21313
BACKLOG-21313: Fix issue with confirmation modal staying open. Ensure workflow contains /jahia/workflow

BACKLOG-21313: Fix issue with confirmation modal staying open.

---

src/javascript/ContentEditorApi/ContentEditorError/ContentEditorError.jsx

https://jira.jahia.org/browse/BACKLOG-21333

BACKLOG-21333: update location by removing hash if error

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormServiceImpl.java
tests/cypress/e2e/contentEditorForm.cy.ts
tests/jahia-module/src/main/resources/META-INF/jahia-content-editor-forms/forms/cent_contentRetrievalCETest.json
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

https://jira.jahia.org/browse/BACKLOG-21331
If labels can contains @ and "resources." or they can contain moduelName@key 

BACKLOG-21331: Fix resolution of labels from resourceBundles and add test

---

.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
tests/cypress/e2e/copyFromOneLanguageToCurrentLanguage.cy.ts

https://jira.jahia.org/browse/TECH-1325
add test copyFromOneLanguageToCurrentLanguage

TECH-1325 add test copyFromOneLanguageToCurrentLanguage

---

src/javascript/DesignSystem/DatePicker/DatePicker.jsx

https://jira.jahia.org/browse/QA-14886

QA-14886: Add missing locales and fallback

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
pom.xml
tests/provisioning-manifest-build.yml

https://jira.jahia.org/browse/BACKLOG-22114

BACKLOG-22114: Update scm tag

---

.github/workflows/on-merge.yml
.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-22114
Regex was invalid for GA so it did not trigger the on-merge wf (on *_X branches).
After the merge, I'll port the fix on the maintenance branches

BACKLOG-22114: Fix regex issue in wf trigger

---

.github/workflows/on-merge.yml

https://jira.jahia.org/browse/BACKLOG-22114
Publish job was skipped because of a wrong branch name

BACKLOG-22114: Fix publish job

---

.github/workflows/nightly.yml

TECH-1573: Enabled manual trigger of content-editor nightlys

---

src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.js
src/javascript/SelectorTypes/Picker/configs/mediaPicker/useMediaPickerInputData.spec.js

https://jira.jahia.org/browse/BACKLOG-22200
Change the order  height x width to width x height for the media Picker card

change order with and height for media Picker card info

---

pom.xml
src/javascript/SelectorTypes/Picker/JahiaPicker/SelectionHandler.jsx
tests/env.run.sh

https://jira.jahia.org/browse/QA-15097
CE backport for https://github.com/Jahia/jcontent/pull/1179

QA-15097: Allow tree item collapse with selection

---

src/javascript/SelectorTypes/RichText/RichText.utils.js

https://jira.jahia.org/browse/BACKLOG-22495
bug fixed, add decodeURIComponent to have the proper system name

bug fixed, add decodeURIComponent to have the proper system name

---

pom.xml
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/test/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImplTest.java
tests/Dockerfile
tests/jahia-module/pom.xml

https://jira.jahia.org/browse/QA-15148
- Needs to be added

QA-15148: Move EditorFormField in target section/fieldset

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-22393
Apply moonstone fix for dropdown icons with smaller images https://github.com/Jahia/moonstone/pull/416

BACKLOG-22393: Bump to latest moonstone version

---

.github/workflows/get-dependencies-updates.yml
.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml
.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1639

TECH-1639: Updated GitHub Actions versions

---

.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
src/javascript/editorTabs/EditPanelContent/FormBuilder/Field/Field.scss
src/javascript/editorTabs/EditPanelContent/FormBuilder/FieldSet/FieldSet.scss
tests/cypress/e2e/contentEditorForm.cy.ts
tests/cypress/e2e/usagesScreen.cy.ts
tests/env.run.sh
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties
tests/provisioning-manifest-build.yml

https://jira.jahia.org/browse/QA-14545
backport PR for https://github.com/Jahia/jcontent/pull/1230 and https://github.com/Jahia/jcontent/pull/1231

QA-14545: Fix html formatting issues with field helpers

---

src/javascript/editorTabs/AdvancedOptions/VanityUrls/VanityUrls.jsx
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/e2e/contentEditorForm.cy.ts
tests/cypress/page-object/fields/smallTextField.ts
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

https://jira.jahia.org/browse/BACKLOG-22904
Collection of backports for content-editor 4.8-SN
* [QA-14983](https://jira.jahia.org/browse/QA-14983) - CE 4.8-SN backport from https://github.com/Jahia/jcontent/pull/1044
* [QA-14593](https://jira.jahia.org/browse/QA-14593) - backports on CE 4.8-SN and jcontent 2.15-SN (from https://github.com/Jahia/content-editor/pull/1681 and https://github.com/Jahia/jcontent/pull/899)
* [QA-15002](https://jira.jahia.org/browse/QA-15002) - backport to CE 4.8-SN (from https://github.com/Jahia/jcontent/pull/1055)
* [QA-14793](https://jira.jahia.org/browse/QA-14793) - Reimplemented original PR for CE 4.8-SN (from https://github.com/Jahia/content-editor/pull/1657 and https://github.com/Jahia/content-editor/pull/1669)

BACKLOG-22904: Collection of backport fixes 

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-22908

BACKLOG-22908: Update module signature

---

tests/provisioning-manifest-snapshot.yml

https://jira.jahia.org/browse/BACKLOG-22908: Update provisioning-manifest-snapshot.yml with latest module versions

BACKLOG-22908: Update provisioning-manifest-snapshot.yml

---

tests/provisioning-manifest-build.yml

https://jira.jahia.org/browse/BACKLOG-22908: Update provisioning-manifest-build.yml with latest module versions

BACKLOG-22908: Update provisioning-manifest-build.yml

---

src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java

https://jira.jahia.org/browse/QA-15247
jcontent backport from https://github.com/Jahia/jcontent/pull/1108 to remove invalid error message

QA-15247: Remove invalid error message

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-23182

BACKLOG-23182: Bump parent version to 8.1.3.0

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-23182

BACKLOG-23182: Add missing parameter for the Slack notif

---

tests/Dockerfile

https://jira.jahia.org/browse/BACKLOG-23184
In order to have run without infra issues we had to fix the versions of Node and the browsers

BACKLOG-23184: Fix the Node and browsers versions

---

package.json
yarn.lock

https://jira.jahia.org/browse/QA-15350

QA-15350: Update @jahia/data-helper version

---

pom.xml
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormFieldSet.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormSection.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormSectionDefinition.java
src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormService.java
src/main/java/org/jahia/modules/contenteditor/api/forms/impl/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/graphql/api/GqlEditorForms.java
tests/cypress/e2e/jsonOverridestest.cy.ts
tests/cypress/page-object/contentEditor.ts
tests/cypress/page-object/fields/dropdownField.ts
tests/cypress/page-object/fields/field.ts
tests/cypress/page-object/fields/index.ts
tests/cypress/page-object/fields/multipleLeftRightField.ts
tests/jahia-module/src/main/java/org/jahia/modules/choicelistinitializer/AnimeHeroInitializer.java
tests/jahia-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/src/main/resources/META-INF/jahia-content-editor-forms/fieldsets/cent_listeZigzag.json
tests/jahia-module/src/main/resources/META-INF/jahia-content-editor-forms/forms/cent_listeZigzag.json
tests/jahia-module/src/main/resources/resources/content-editor-test-module_en.properties

…
https://jira.jahia.org/browse/QA-15345

QA-15345: Handle merges of static definitions from fieldsets for primary node type and mixins correctly.

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-23359

BACKLOG-23359: Bump Jahia parent version

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-23486
Fix the signature issue by updating the related action parameters: https://github.com/Jahia/jcontent/blob/2_x/.github/workflows/on-release.yml#L36-L53

BACKLOG-23486: Fix the signature update issue

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

Fixed some labels in French and German.

feat: fix labels in FR and DE

---

tests/cypress/e2e/textFieldInitializerTest.cy.ts

- Added a refresh page composer before doing the delete permanently.
- Also changed the selector path to target the correct div.

test: add a refresh + change selector path

---

src/main/resources/javascript/locales/fr.json

https://github.com/Jahia/content-editor/issues/1818

fix: correct french typos

---

tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

Update provisioning with latest release of jcontent and site-settings-seo.

test: update provisioning with latest release
